import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fixture} from './helpers/memory-models.mjs';
import {OwnerControls,migrateOwner} from '../lib/console/owner.mjs';
import {CONSOLE_WRITE_SCOPES} from '../../shared/console-contract.mjs';
import {MemoryWorker} from '../lib/memory-jobs/worker.mjs';
import {assertProtection} from '../lib/lifecycle/protection.mjs';
const model={enabled:true,protocol:'openai_compatible',base_url:'https://synthetic.example.invalid/v1',model:'synthetic-only',profile_revision:'1',daily_requests:20,output_tokens:4096,batch_size:2,sensitivities:['public','internal','sensitive'],egress_approved:true,query_approved:true};
function setup(t){const f=fixture(t),{s}=f,user=f.auth.user_id,c=s.issueCredential({userId:user,label:'Synthetic owner',deviceId:'synthetic',agentId:'mnemuron-console',agentInstanceId:'synthetic',scopes:CONSOLE_WRITE_SCOPES}),auth=s.authenticate(c.api_key),service=s.consoleService;
 s.memoryConfig={...s.memoryConfig,console:{owner_user_id:user,worker_enabled:false}};s.memoryTransaction(()=>migrateOwner(s.db,user,{memory:true,capture:false,handoff:false,connections:true}));service.owner=new OwnerControls(service);
 const act=(action,payload)=>service.execute(auth,{action,payload,operation_id:randomUUID()});let calls=0;
 s.db.prepare('INSERT INTO console_models(user_id,kind,revision,config_json,secret_cipher,updated_at) VALUES(?,?,1,?,NULL,?)').run(user,'organizer',JSON.stringify(model),Date.now());
 const real=service.models.provider.bind(service.models);service.models.provider=(user,kind,options)=>{const p=real(user,kind,options);p.generateStructured=async(input,schema,{reserve})=>{reserve();calls++;return {data:{results:input.sources.map(m=>input.operation==='entities'?{memory_id:m.memory_id,revision:m.revision,objects:[]}:input.operation==='summary'?{memory_id:m.memory_id,revision:m.revision,start:0,end:m.content.length,quote:m.content}:{memory_id:m.memory_id,category:'uncategorized',tags:[]})}};};return p;};
 return {...f,auth,user,service,owner:service.owner,act,calls:()=>calls};}
const enable=f=>f.act('features.save',{expected_revision:f.owner.policy().revision,flags:{processing:true,classification:true}});
const preview=f=>f.act('processing.preview',{kind:'classification',limit:2,budget:1});
test('HARDEN-OWNER all owner actions reject a foreign subject; run IDs never cross owner boundaries',async t=>{
 const f=setup(t);f.save('Synthetic owner boundary');
 for(const action of ['features.save','schedule.save','processing.preview','processing.start','processing.pause','processing.resume','processing.cancel']){
  await assert.rejects(f.service.execute({...f.auth,user_id:'synthetic-other-owner'},{action,payload:{},operation_id:randomUUID()}));
 }
 const p=await preview(f);
 f.s.memoryTransaction(()=>f.s.db.prepare('UPDATE owner_processing_runs SET user_id=? WHERE run_id=?').run('synthetic-other-owner',p.run_id));
 for(const action of ['processing.start','processing.pause','processing.resume','processing.cancel']){
  await assert.rejects(f.act(action,{run_id:p.run_id,...(['processing.start','processing.resume'].includes(action)?{digest:p.digest}:{})}),e=>e.errorCode==='RUN_NOT_FOUND');
 }
 assert.equal(f.s.db.prepare('SELECT state FROM owner_processing_runs WHERE run_id=?').get(p.run_id).state,'preview');
 assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM owner_processing_jobs').get().n,0);assert.equal(f.calls(),0);
});
test('owner migration is explicit, protected, idempotent and initially paused',async t=>{const f=setup(t);assertProtection(f.s.db);assert.equal(f.owner.policy().flags.processing,false);assert.equal(f.owner.policy().schedule.enabled,false);const before=f.owner.policy();f.s.memoryTransaction(()=>migrateOwner(f.s.db,f.user,{memory:false}));assert.deepEqual(f.owner.policy(),before);await f.service.tick();assert.equal(f.calls(),0);});
test('only exact owner with console write scopes can save; old scheduling paths denied',async t=>{const f=setup(t);for(const auth of [{...f.auth,user_id:'other'},{...f.auth,agent_id:'chatgpt-web'},{...f.auth,scopes:['console:read']}])await assert.rejects(f.service.execute(auth,{action:'features.save',payload:{expected_revision:0,flags:{processing:true}},operation_id:randomUUID()}));for(const action of ['jobs.schedule','jobs.retry','vector.prepare','vector.schedule'])await assert.rejects(f.act(action,{}),e=>e.errorCode==='EXECUTION_GRANT_REQUIRED');});
test('saving enabled flags never schedules legacy outbox or consumes legacy jobs',async t=>{const f=setup(t);for(let i=0;i<3;i++)f.save('Synthetic record '+i);const s=f.s.derivedMemory.currentSource(f.user,f.s.db.prepare('SELECT memory_id FROM memories LIMIT 1').get().memory_id),p=f.service.models.provider(f.user,'organizer');const id=f.s.memoryJobs.enqueue({userId:f.user,type:'classification',scope:s.scope_key,profile:p.profile.fingerprint,metadata:{},items:[s]});const before=f.s.db.prepare('SELECT * FROM memory_processing_outbox').all();await enable(f);await f.service.tick();assert.equal(f.calls(),0);assert.equal(f.s.memoryJobs.get(id).state,'pending');assert.deepEqual(f.s.db.prepare('SELECT * FROM memory_processing_outbox').all(),before);assert.equal(f.s.memoryJobs.claim('old',{userId:f.user,profile:p.profile.fingerprint}),null);});
test('preview is inert; explicit digest starts only bounded manifest within total budget',async t=>{const f=setup(t);for(let i=0;i<4;i++)f.save('Synthetic record '+i);await enable(f);const p=await preview(f);assert.equal(p.count,2);assert.equal(f.calls(),0);await assert.rejects(f.act('processing.start',{run_id:p.run_id,digest:'wrong'}));await f.act('processing.start',{run_id:p.run_id,digest:p.digest});await f.service.tick();assert.equal(f.calls(),1);const run=f.owner.run(f.user,p.run_id);assert.equal(run.state,'completed');assert.equal(run.used,1);assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM memory_annotations').get().n,2);});
test('pause fences leases and save never resumes them',async t=>{const f=setup(t);f.save('Synthetic');await enable(f);const p=await preview(f);await f.act('processing.start',{run_id:p.run_id,digest:p.digest});const r=f.owner.run(f.user,p.run_id),job=f.s.memoryJobs.claim('synthetic',{userId:f.user,profile:r.profile,runId:r.run_id});await f.act('processing.pause',{run_id:r.run_id});assert.equal(f.s.memoryJobs.owns(job),false);assert.throws(()=>f.owner.guard(r.run_id));await enable(f);await f.service.tick();assert.equal(f.calls(),0);assert.equal(f.owner.run(f.user,r.run_id).state,'paused');});
test('preview cannot bypass start through pause/resume; changed models invalidate grants',async t=>{const f=setup(t);f.save('Synthetic');await enable(f);const p=await preview(f);await assert.rejects(f.act('processing.pause',{run_id:p.run_id}));f.s.db.prepare('UPDATE console_models SET revision=revision+1').run();await assert.rejects(f.act('processing.start',{run_id:p.run_id,digest:p.digest}),e=>e.errorCode==='MODEL_VERSION_CHANGED');assert.equal(f.calls(),0);});
test('automatic rules bind model revisions and only new records; saving does not execute',async t=>{const f=setup(t);f.save('Old synthetic');await enable(f);await f.act('schedule.save',{expected_revision:f.owner.policy().revision,enabled:true,kinds:['classification'],interval_minutes:5,max_items:2,budget:1});assert.equal(f.calls(),0);const old=f.s.db.prepare('SELECT memory_id FROM memories').get().memory_id;const fresh=f.save('New synthetic').memory_id;const p=f.owner.policy();f.s.db.prepare('UPDATE owner_feature_policy SET schedule_json=?').run(JSON.stringify({...p.schedule,next_at:0}));await f.service.tick();assert.equal(f.calls(),1);assert.deepEqual(f.s.db.prepare('SELECT memory_id FROM memory_annotations').all().map(r=>r.memory_id),[fresh]);assert.notEqual(old,fresh);
 f.s.db.prepare('UPDATE console_models SET revision=revision+1').run();const q=f.owner.policy();f.s.db.prepare('UPDATE owner_feature_policy SET schedule_json=?').run(JSON.stringify({...q.schedule,next_at:0}));await f.service.tick();assert.equal(f.owner.policy().schedule.enabled,false);assert.equal(f.owner.policy().schedule.error_code,'MODEL_VERSION_CHANGED');});
test('in-flight cancellation never publishes output',async t=>{const f=setup(t);f.save('Synthetic delayed');await enable(f);const p=await preview(f);await f.act('processing.start',{run_id:p.run_id,digest:p.digest});let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r),base=f.service.models.provider;f.service.models.provider=(...a)=>{const p=base(...a),gen=p.generateStructured;p.generateStructured=async(...args)=>{const output=await gen(...args);entered();await gate;return output;};return p;};const tick=f.service.tick();await started;await f.act('processing.cancel',{run_id:p.run_id});release();await tick;assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM memory_annotations').get().n,0);assert.equal(f.owner.run(f.user,p.run_id).state,'cancelled');assert.equal(f.calls(),1);});
test('143060 legacy outbox entries stay unchanged when all processing channels are enabled',async t=>{const f=setup(t);f.s.db.exec(`WITH RECURSIVE n(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM n WHERE x<143060) INSERT INTO memory_processing_outbox(user_id,memory_id,revision,job_type,state,content_hash,created_at) SELECT '${f.user}','synthetic-legacy-'||x,1,'classification','scheduled','synthetic-hash','2020-01-01T00:00:00.000Z' FROM n`);await f.act('features.save',{expected_revision:0,flags:{processing:true,classification:true,summary:true,entities:true,vector_build:true}});await f.service.tick();assert.equal(f.calls(),0);assert.equal(f.s.db.prepare("SELECT COUNT(*) n FROM memory_processing_outbox WHERE state='scheduled'").get().n,143060);assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM owner_processing_runs').get().n,0);});
test('vector grant builds only manifest and never activates automatically',async t=>{const f=setup(t);const {MockVectorStore}=await import('./helpers/vector-mock.mjs');f.s.memoryConfig.vector_store={enabled:true,collection_prefix:'synthetic_owner'};const backend=new MockVectorStore();f.service.vectorBackend=()=>backend;f.service.probeVerified=()=>true;f.s.db.prepare('INSERT INTO console_models(user_id,kind,revision,config_json,secret_cipher,updated_at) VALUES(?,?,1,?,NULL,?)').run(f.user,'embedder',JSON.stringify({...model,dimensions:3}),Date.now());let calls=0;const base=f.service.models.provider;f.service.models.provider=(...a)=>{const p=base(...a);if(a[1]==='embedder')p.embed=async(texts,type,{reserve})=>{reserve();calls++;return {vectors:texts.map(()=>[1,0,0])};};return p;};f.save('Synthetic vector one');f.save('Synthetic vector two');await f.act('features.save',{expected_revision:0,flags:{processing:true,vector_build:true}});const p=await f.act('processing.preview',{kind:'vector',limit:1,budget:1});await f.act('processing.start',{run_id:p.run_id,digest:p.digest});await f.service.tick();await f.service.tick();assert.equal(calls,1);assert.equal(f.owner.run(f.user,p.run_id).state,'completed');assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM memory_vector_owner_active').get().n,0);});
test('restart preserves paused state; compatible rollback retains newer data and additive schema',async t=>{const f=setup(t);f.save('Synthetic retained after migration');const fs=await import('node:fs');f.s.db.exec('PRAGMA wal_checkpoint(TRUNCATE)');const copy=f.root+'/rollback.sqlite3';fs.copyFileSync(f.root+'/synthetic.sqlite3',copy);const {MnemuronStore:NewStore}=await import('../lib/store.mjs');let restored=new NewStore(copy,{memoryConfig:f.s.memoryConfig});assert.equal(restored.consoleService.owner.policy().flags.processing,false);assert.equal(restored.db.prepare('SELECT COUNT(*) n FROM memories').get().n,1);restored.close();const oldSource=new URL('../../../../audit-refinement/source/server/lib/store.mjs',import.meta.url);if(!fs.existsSync(oldSource))return;const {MnemuronStore:BaselineStore}=await import(oldSource);const baseline=structuredClone(f.s.memoryConfig);delete baseline.console.owner_user_id;restored=new BaselineStore(copy,{memoryConfig:baseline});assert.equal(restored.db.prepare('SELECT COUNT(*) n FROM memories').get().n,1);assert.equal(restored.db.prepare('SELECT COUNT(*) n FROM owner_feature_policy').get().n,1);assert.equal(restored.memoryConfig.console.worker_enabled,false);restored.close();});
test('revoking the credential that authorized a run blocks it even if another console credential exists',async t=>{const f=setup(t);f.save('Synthetic');await enable(f);const p=await preview(f);await f.act('processing.start',{run_id:p.run_id,digest:p.digest});f.s.issueCredential({userId:f.user,label:'Another synthetic',deviceId:'second',agentId:'mnemuron-console',agentInstanceId:'second',scopes:CONSOLE_WRITE_SCOPES});f.s.db.prepare('UPDATE credentials SET revoked_at=? WHERE credential_id=?').run(new Date().toISOString(),f.auth.credential_id);await f.service.tick();assert.equal(f.calls(),0);assert.equal(f.owner.run(f.user,p.run_id).error_code,'OWNER_CREDENTIAL_INACTIVE');});
test('summary and entities require their own switches and do not enable classification',async t=>{for(const kind of ['summary','entities']){const f=setup(t);f.save('Synthetic channel record');await f.act('features.save',{expected_revision:0,flags:{processing:true,[kind]:true}});const denied=await preview(f);await assert.rejects(f.act('processing.start',{run_id:denied.run_id,digest:denied.digest}),e=>e.errorCode==='PROCESSING_PAUSED');const p=await f.act('processing.preview',{kind,limit:1,budget:1});await f.act('processing.start',{run_id:p.run_id,digest:p.digest});await f.service.tick();assert.equal(f.owner.run(f.user,p.run_id).state,'completed',kind);assert.equal(f.calls(),1);assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM memory_annotations').get().n,0);}});
test('a partial job stops at the run budget without publishing an incomplete result',async t=>{const f=setup(t);for(let i=0;i<3;i++)f.save('Synthetic bounded '+i);await enable(f);const p=await f.act('processing.preview',{kind:'classification',limit:3,budget:1});await f.act('processing.start',{run_id:p.run_id,digest:p.digest});await f.service.tick();assert.equal(f.calls(),1);assert.equal(f.owner.run(f.user,p.run_id).state,'blocked');assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM memory_annotations').get().n,0);});
test('explicit migration CLI initializes a populated isolated database without running work',async t=>{const f=fixture(t);f.save('Synthetic pre-migration');const fs=await import('node:fs'),{execFileSync}=await import('node:child_process');const config={...f.s.memoryConfig,console:{worker_enabled:false},jobs:{enabled:false}};const file=f.root+'/runtime.json';fs.writeFileSync(file,JSON.stringify(config),{mode:0o600});const result=JSON.parse(execFileSync(process.execPath,[new URL('../bin/mnemuron-owner-migrate.mjs',import.meta.url).pathname,f.root+'/synthetic.sqlite3',file,f.auth.user_id,'--apply-paused'],{encoding:'utf8'}));assert.equal(result.processing,false);assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM owner_processing_runs').get().n,0);assert.equal(f.s.db.prepare('SELECT COUNT(*) n FROM memories').get().n,1);});

test('all owner status views reflect Web processing policy rather than the paused legacy worker',async t=>{const f=setup(t);assert.equal(f.service.capabilities(f.auth).worker_enabled,false);await enable(f);assert.equal(f.service.capabilities(f.auth).worker_enabled,true);const {consoleRead}=await import('../lib/console-read.mjs');assert.equal((await consoleRead(f.s,f.auth,'jobs')).worker_enabled,true);assert.equal((await consoleRead(f.s,f.auth,'system-health')).services.worker,'enabled_not_probed');await f.act('schedule.save',{expected_revision:f.owner.policy().revision,enabled:true,kinds:['classification'],interval_minutes:5,max_items:1,budget:1});assert.equal(f.service.settings(f.user).schedule_enabled,true);assert.equal(f.calls(),0);});

test('SEARCH-OWNER: explicit request, saved owner preference, runtime mode, then hybrid; lexical has no provider use',async t=>{
 const f=setup(t);f.save('Synthetic searchable configuration');let calls=0;
 f.service.models.provider=()=>{calls++;throw new Error('Lexical must never allocate a provider');};
 f.service.vector=()=>{calls++;throw new Error('Lexical must never query vectors');};
 assert.equal(f.s.defaultRetrievalMode(f.auth),'hybrid');
 f.s.memoryConfig.memory={retrieval:{mode:'lexical'}};assert.equal(f.s.defaultRetrievalMode(f.auth),'lexical');
 const initial=await f.s.searchMemories(f.auth,{query:'searchable'});assert.equal(initial.retrieval.requested_mode,'lexical');
 await f.act('features.save',{expected_revision:f.owner.policy().revision,flags:{},retrieval_mode:'lexical'});
 f.s.memoryConfig.memory.retrieval.mode='hybrid';assert.equal(f.s.defaultRetrievalMode(f.auth),'lexical');
 assert.equal(f.service.capabilities(f.auth).default_retrieval_mode,'lexical');
 const {consoleRead}=await import('../lib/console-read.mjs');assert.equal((await consoleRead(f.s,f.auth,'memories',{query:'searchable'})).retrieval.requested_mode,'lexical');
 await f.act('features.save',{expected_revision:f.owner.policy().revision,flags:{},retrieval_mode:'semantic'});
 assert.equal((await f.s.searchMemories(f.auth,{query:'searchable',mode:'lexical'})).retrieval.requested_mode,'lexical');assert.equal(calls,0);
});
