export const catalog={
 'zh-CN':{
  consoleLogin:'登录管理控制台',consoleLoginNote:'管理自己的记忆和连接。此登录不会自动向 ChatGPT 授权。',oauthLogin:'连接 ChatGPT',oauthLoginNote:'先验证你的 Mnemuron 账户，再明确允许只读访问。这不会登录管理控制台。',oauthConsent:'允许 ChatGPT 只读访问',oauthRestartHelp:'此链接只用于本次授权，并非固定的集成页面。请关闭此页，回到 ChatGPT 重新发起连接。',oauthRetry:'重试本次授权',
  overview:'概览',memories:'记忆库',summaries:'分类与摘要',jobs:'整理任务',connections:'连接管理',models:'模型配置',security:'账户安全',audit:'审计记录',storage:'存储与备份',appearance:'外观设置',invitations:'注册码管理',accounts:'账户管理',handoff:'Handoff · 延后',
  workspace:'我的空间',settings:'连接与设置',platform:'平台管理 · 权限待定',brandNote:'个人记忆，持续连接。',hero:'你的记忆，井然有序。',heroNote:'保留每条信息的来源，让上下文在会话间延续。',
  login:'登录 Mnemuron',register:'创建你的账户',recover:'账户恢复',username:'用户名',password:'密码',otp:'动态验证码',invitation:'一次性注册码',continue:'继续',signIn:'登录',signOut:'退出当前会话',cancel:'取消',allow:'允许只读访问',
  authNote:'请使用 Mnemuron 账户，不要输入 ChatGPT 密码。',inviteNote:'注册码由服务器管理员签发，仅可使用一次。',totp:'绑定验证器',totpNote:'使用验证器扫描二维码，或手动输入密钥。密钥只在绑定期间可见。',verify:'验证并继续',copy:'复制',copied:'已复制',showPassword:'显示密码',hidePassword:'隐藏密码',
  recoveryCodes:'保存恢复码',recoveryNote:'这些恢复码仅显示一次。请离线保存，不要上传或分享。',acknowledge:'我已保存恢复码',pending:'正在等待安全绑定',pendingNote:'MFA 已验证。核心身份供应与恢复码确认全部完成后才能登录。',registered:'注册完成，请正常登录',
  blocked:'策略待确认',blockedNote:'此操作尚未获准。页面展示不代表操作已开放。',unavailable:'暂不可用',retry:'重试',loading:'正在加载…',empty:'目前没有可显示的记录',noConnection:'尚无已授权连接',authenticated:'已验证账户',restartAuthorization:'账户或授权会话已变化。请返回请求连接的应用，重新发起授权。',
  search:'搜索记忆',query:'搜索内容',readOnly:'只读',memoryCount:'原子记忆',sourceCount:'来源记录',summaryCount:'摘要',jobCount:'整理任务',recent:'最近的记忆',viewAll:'查看全部',detail:'记忆详情',sources:'来源',revisions:'版本',next:'下一页',previous:'上一页',close:'关闭',complete:'内容已完整读取',changed:'来源或版本已变化，请重新读取。',
  appearanceNote:'配色不改变布局、功能或权限。偏好按账户分别保存。',theme:'颜色主题',mode:'明暗模式',language:'语言',light:'浅色',dark:'深色',a:'Neural Indigo',b:'Signal Teal',c:'Paper Amber',
  securityNote:'登录需要密码与动态验证码。恢复证明组合尚待确认，不启用弱恢复。',modelsNote:'模型资源与费用策略待确认。不显示密钥或其他账户配置。',storageNote:'只展示本人记录的统计。整库备份、恢复与下载不在网页权限内。',platformNote:'当前账户没有平台管理授权。此页不返回其他账户的身份或统计。',
  error:'请求未完成',errorNote:'请返回并重试。未授权、过期或依赖故障不会跳过安全校验。',identity:'当前账户',state:'状态',created:'创建时间',scope:'范围',status:'状态',consent:'授权连接',consentNote:'仅允许读取你授权的记忆和项目。不会写入记忆、切换任务或确认 Resume。',
  policy:'权限边界',pendingPolicies:'未批准操作保持关闭',notProduction:'尚未生产晋级',noDemo:'所有数据来自当前账户；不可用时不会显示演示数据。',newMemory:'新建记忆',organize:'手动整理',export:'导出记忆',restore:'整库恢复',configure:'修改配置',issue:'网页签发',manage:'角色管理',revoke:'撤销授权',
  passwordConfirm:'再次输入密码',alreadyShown:'密钥已显示过。本页不会重新展示；请使用已保存的验证器或恢复码。',oauthClient:'请求连接的应用',scopeIdentity:'识别你的 Mnemuron 账户',scopeOffline:'使用可撤销、轮换的刷新令牌保持连接',scopeMemory:'读取你授权的记忆',scopeProject:'读取你授权的项目上下文',systemLabel:'个人记忆系统',workspaceLabel:'个人工作空间',heroLabel:'让记忆持续连接',passwordTotp:'密码与动态验证码',back:'返回安全入口',expired:'此步骤已过期，请从安全入口重新开始。',loginFailed:'登录信息无效或账户尚不可用。请检查凭证后重试。',rateLimited:'尝试过于频繁，请稍后重试。',pendingStep:'此步骤暂不可用，请重新检查当前注册状态。',
 },
 en:{
  consoleLogin:'Sign in to the console',consoleLoginNote:'Manage your memories and connections. This sign-in does not authorize ChatGPT.',oauthLogin:'Connect ChatGPT',oauthLoginNote:'Verify your Mnemuron account, then explicitly allow read-only access. This does not sign you in to the console.',oauthConsent:'Allow ChatGPT read-only access',oauthRestartHelp:'This link belongs to one authorization request, not a permanent integration page. Close this page and start a new connection from ChatGPT.',oauthRetry:'Retry this authorization',
  overview:'Overview',memories:'Memory library',summaries:'Categories & summaries',jobs:'Organizer jobs',connections:'Connections',models:'Model settings',security:'Account security',audit:'Audit log',storage:'Storage & backup',appearance:'Appearance',invitations:'Registration codes',accounts:'Accounts',handoff:'Handoff · deferred',
  workspace:'My workspace',settings:'Connections & settings',platform:'Platform · policy pending',brandNote:'Personal memory. Lasting context.',hero:'Your memory, thoughtfully organized.',heroNote:'Keep the provenance of every detail. Carry context across conversations.',
  login:'Sign in to Mnemuron',register:'Create your account',recover:'Account recovery',username:'Username',password:'Password',otp:'Authenticator code',invitation:'One-time registration code',continue:'Continue',signIn:'Sign in',signOut:'Sign out of this session',cancel:'Cancel',allow:'Allow read-only access',
  authNote:'Use your Mnemuron account, not your ChatGPT password.',inviteNote:'Registration codes are issued by your operator and can only be used once.',totp:'Connect your authenticator',totpNote:'Scan the QR code or enter the key manually. The key is available only during enrollment.',verify:'Verify and continue',copy:'Copy',copied:'Copied',showPassword:'Show password',hidePassword:'Hide password',
  recoveryCodes:'Save your recovery codes',recoveryNote:'These codes are shown once. Store them offline. Do not upload or share them.',acknowledge:'I have saved my recovery codes',pending:'Waiting for secure identity binding',pendingNote:'MFA is verified. Login requires completed Core provisioning and recovery-code acknowledgement.',registered:'Registration complete. Please sign in.',
  blocked:'Policy pending',blockedNote:'This operation has not been approved. Visibility does not grant permission.',unavailable:'Currently unavailable',retry:'Retry',loading:'Loading…',empty:'No records to display yet',noConnection:'No authorized connection yet',authenticated:'Verified account',restartAuthorization:'The account or authorization session changed. Return to the requesting application and start a new authorization.',
  search:'Search memories',query:'Search query',readOnly:'Read-only',memoryCount:'Atomic memories',sourceCount:'Source records',summaryCount:'Summaries',jobCount:'Organizer jobs',recent:'Recent memories',viewAll:'View all',detail:'Memory detail',sources:'Sources',revisions:'Revision',next:'Next page',previous:'Previous page',close:'Close',complete:'Complete content returned',changed:'The source or revision changed. Read it again.',
  appearanceNote:'Colors never change layout, capabilities or permissions. Preferences are stored per account.',theme:'Color theme',mode:'Color mode',language:'Language',light:'Light',dark:'Dark',a:'Neural Indigo',b:'Signal Teal',c:'Paper Amber',
  securityNote:'Sign-in requires a password and authenticator code. Recovery proof policy is pending; no weaker recovery is enabled.',modelsNote:'Model resources and cost policy are pending. Keys and other accounts’ configuration are never shown.',storageNote:'Only your record totals are shown. Whole-database backup, restore and download are not web capabilities.',platformNote:'This account has no platform management grant. This page returns no other account identities or statistics.',
  error:'Request not completed',errorNote:'Go back and try again. Authorization, expiry and dependency checks are never bypassed.',identity:'Current account',state:'State',created:'Created',scope:'Scope',status:'Status',consent:'Authorize connection',consentNote:'Read only memories and projects you authorize. No memory writes, task switching or Resume confirmation.',
  policy:'Permission boundary',pendingPolicies:'Unapproved operations stay disabled',notProduction:'Not promoted to production',noDemo:'All data belongs to the current account. No demo fallback when unavailable.',newMemory:'New memory',organize:'Run organizer',export:'Export memories',restore:'Restore database',configure:'Change settings',issue:'Issue in browser',manage:'Manage roles',revoke:'Revoke grant',
  passwordConfirm:'Confirm password',alreadyShown:'The secret was already displayed. It is not shown again; use your saved authenticator or recovery codes.',oauthClient:'Application requesting access',scopeIdentity:'Identify your Mnemuron account',scopeOffline:'Keep this connection with revocable, rotating refresh tokens',scopeMemory:'Read memories you authorize',scopeProject:'Read project context you authorize',systemLabel:'PERSONAL MEMORY SYSTEM',workspaceLabel:'PERSONAL WORKSPACE',heroLabel:'YOUR MEMORY, CONNECTED',passwordTotp:'Password and authenticator code',back:'Return to the safe entry point',expired:'This step expired. Start again from the safe entry point.',loginFailed:'The sign-in details or account are unavailable. Check your credentials and try again.',rateLimited:'Too many attempts. Please try again later.',pendingStep:'This step is unavailable. Check your current registration status.',
 }
};

// Presentation copy is separate from backend status codes and never translates memory content.
Object.assign(catalog['zh-CN'], {
  connectionHeadline:'ChatGPT，接上你的个人记忆。', connectionDescription:'从已授权的记忆中找回上下文。来源、版本与访问范围，始终清晰可查。',
  manageConnections:'管理我的连接', browseMemories:'浏览记忆', ownedRecords:'仅当前账户', recentLabel:'近期记忆', processingLabel:'整理概况',
  memoryProcessing:'记忆整理', atomicNote:'保留原文与版本', derivedNote:'来源关联的派生视图', jobStatusNote:'进入任务页查看执行状态',
  summaryBoundary:'摘要是派生视图，不覆盖原文。遗漏与待核实信息保留在来源中。', viewJobs:'查看整理任务', inspectMemoryNote:'点开任意记忆，查看正文、来源与修订历史。',
  personalizeLabel:'个性化工作空间', fixedLayout:'A · 统一布局', themeName_a:'神经靛蓝', themeName_b:'信号青绿', themeName_c:'纸感琥珀',
  themeNote_a:'柔和靛蓝，清晰专注', themeNote_b:'自然青绿，沉稳明快', themeNote_c:'温暖琥珀，舒适阅读',
  modeNote:'选择适合当前环境的明暗模式。', languageNote:'仅切换界面语言，记忆正文保持原样。',
  appearanceScopeNote:'外观偏好独立保存于当前账户。切换不会改变数据、访问权限或正在填写的内容。',
  authHeadlineFirst:'记住重要的。', authHeadlineSecond:'只属于你的。', authDescription:'用一个独立空间连接你的记忆，让每次对话从理解开始。',
  authEyebrow:'连接到你的记忆空间', accountMenu:'当前账户与退出', authFooter:'Mnemuron · 个人记忆，持续上下文',
  pageNote_memories:'搜索、查看并追溯属于你的每一条记忆。', pageNote_summaries:'分类整理与来源关联的摘要，始终与原始记忆分开。',
  pageNote_jobs:'查看整理任务的进度、结果与需要处理的问题。', pageNote_connections:'在同一处查看你的应用授权和 Agent 连接。',
  pageNote_models:'查看模型配置边界与外发政策。密钥不会在页面回显。', pageNote_security:'管理你的身份、验证器与账户访问。',
  pageNote_audit:'仅查看当前账户的访问与安全事件。', pageNote_storage:'了解个人记录与存储边界。个人数据不等于整库备份。',
  pageNote_appearance:'一种布局，多种心境。让你的记忆空间更适合你。', pageNote_invitations:'查看注册准入规则。签发能力由明确的运维权限控制。',
  pageNote_accounts:'账户管理与个人记忆读取相互独立。',
});
Object.assign(catalog.en, {
  connectionHeadline:'Connect ChatGPT to your personal memory.', connectionDescription:'Find context in memories you authorize. Keep every source, revision and access boundary in view.',
  manageConnections:'Manage my connections', browseMemories:'Browse memories', ownedRecords:'This account only', recentLabel:'RECENT MEMORIES', processingLabel:'PROCESSING',
  memoryProcessing:'Memory organization', atomicNote:'Originals and revisions retained', derivedNote:'Source-linked derived views', jobStatusNote:'Open jobs for execution status',
  summaryBoundary:'Summaries are derived views, not replacements for originals. Check sources for omissions and uncertainty.', viewJobs:'View organizer jobs', inspectMemoryNote:'Open a memory to inspect its content, provenance and revision history.',
  personalizeLabel:'PERSONALIZE YOUR WORKSPACE', fixedLayout:'A · Unified layout', themeName_a:'Neural Indigo', themeName_b:'Signal Teal', themeName_c:'Paper Amber',
  themeNote_a:'Soft indigo. Clear focus.', themeNote_b:'Natural teal. Quiet clarity.', themeNote_c:'Warm amber. Thoughtful reading.',
  modeNote:'Choose the appearance that suits your environment.', languageNote:'Translate the interface, never your original memories.',
  appearanceScopeNote:'Appearance preferences belong to this account. Switching never changes data, access permissions or your current form.',
  authHeadlineFirst:'Remember what matters.', authHeadlineSecond:'Keep it yours.', authDescription:'An independent space for your memories. Start every conversation with context.',
  authEyebrow:'CONNECT TO YOUR MEMORY', accountMenu:'Current account and sign out', authFooter:'Mnemuron · Personal memory, continuous context',
  pageNote_memories:'Search, inspect and trace every memory in your own space.', pageNote_summaries:'Source-linked categories and summaries, kept separate from original memories.',
  pageNote_jobs:'Inspect organizer progress, results and items that need attention.', pageNote_connections:'Review your application grants and Agent connections in one place.',
  pageNote_models:'Review model boundaries and egress policy. Secret keys are never displayed.', pageNote_security:'Your identity, authenticator and account access.',
  pageNote_audit:'Access and security events for the current account only.', pageNote_storage:'Understand your record totals. Personal data is not a whole-database backup.',
  pageNote_appearance:'One layout, a different mood. Make this memory space yours.', pageNote_invitations:'Review registration rules. Issuance requires explicit operator permission.',
  pageNote_accounts:'Account administration does not grant access to personal memories.',
});

Object.assign(catalog["zh-CN"],{
  "interactive": "可操作",
  "actions": "操作",
  "refresh": "刷新",
  "save": "保存",
  "confirm": "确认执行",
  "content": "记忆内容",
  "memoryType": "记忆类型",
  "topic": "主题（可选）",
  "scopeTarget": "范围 ID（个人级留空）",
  "user": "个人",
  "project": "项目",
  "task": "任务",
  "workstream": "工作分支",
  "session": "会话",
  "fact": "事实",
  "goal": "目标",
  "constraint": "约束",
  "decision": "决定",
  "completed": "已完成事项",
  "blocker": "阻碍",
  "remaining": "剩余事项",
  "next_step": "下一步",
  "editMemory": "修订记忆",
  "retractMemory": "撤回记忆",
  "classifyMemory": "手动分类",
  "sensitivity": "敏感级别",
  "webVisibility": "ChatGPT 可见性",
  "reason": "变更原因",
  "category": "分类",
  "sensitive": "敏感",
  "internal": "内部",
  "public": "公开可外发",
  "secret": "机密（不外发）",
  "allowChatGPT": "允许 ChatGPT 读取当前版本",
  "grantRevisionNote": "授权仅适用于当前版本。修订后自动失效；机密记录不能授权外发。",
  "sensitivityNote": "更改分类会撤销旧的 ChatGPT 授权，并使相关摘要和索引失效。公开记录无需单独授权。",
  "retractNote": "撤回后不再作为有效记忆检索；原文和历史保留，不物理删除。",
  "jobType": "整理类型",
  "classification": "自动分类",
  "summary": "生成摘要",
  "summarize": "生成摘要",
  "timezone": "时区",
  "includeOpen": "本次包含尚未结束的周期",
  "enablePeriodic": "启用定期分类与每日／每周汇总",
  "organizeCostNote": "任务交给后台 worker 执行，可能向已批准的模型发送选中范围内的原文并产生费用。未配置模型时不会伪报完成。",
  "scheduleStatus": "周期整理",
  "enabled": "已启用",
  "disabled": "已关闭",
  "progress": "处理进度",
  "cancelJob": "取消任务",
  "vectorIndex": "向量索引",
  "organizer": "分类与摘要模型",
  "embedder": "向量模型",
  "testModel": "测试连接",
  "modelBoundary": "模型与数据边界",
  "modelBoundaryNote": "模型配置只属于当前账户。密钥加密保存且不回显。外发需要明确批准，内网服务需要部署管理员允许。",
  "vectorNotConfigured": "尚未配置 Qdrant 后端；向量重建需先完成服务端配置。字面检索仍可使用。",
  "rebuildIndex": "重建我的向量索引",
  "hasKey": "已保存密钥",
  "yes": "是",
  "no": "否",
  "protocol": "接口协议",
  "baseUrl": "模型服务地址",
  "modelName": "模型名称",
  "modelRevision": "模型版本标识",
  "apiKey": "API 密钥（空白保留）",
  "removeKey": "删除已保存的密钥",
  "dimensions": "向量维度",
  "dailyRequests": "每日调用上限",
  "outputTokens": "输出 Token 上限",
  "batchSize": "每批记忆数量",
  "modelSensitivity": "模型允许处理的最高敏感级别",
  "approveEgress": "我允许将所选级别的记忆发送至此模型",
  "approveQuery": "我也允许发送搜索词以进行语义检索",
  "keyWriteOnlyNote": "密钥仅可写入，服务不会返回原密钥。跨站点更换服务地址时，必须重新填写密钥。",
  "probeCostNote": "此测试发送合成文本，不发送个人记忆，但真实模型可能计费，并计入每日限额。",
  "chatgptGrants": "ChatGPT 授权",
  "agentConnections": "Agent 连接",
  "mcpEndpoint": "MCP 地址",
  "expires": "到期时间",
  "addConnection": "添加连接",
  "label": "连接名称",
  "agentId": "Agent 标识",
  "deviceId": "设备标识",
  "access": "访问权限",
  "read": "只读记忆",
  "read_write": "读取和显式保存",
  "rotateKey": "轮换密钥",
  "revoked": "已撤销",
  "active": "有效",
  "managedConnection": "系统／运维管理",
  "accountSecurity": "账户安全操作",
  "changePassword": "修改密码",
  "changeTotp": "更换验证器",
  "rotateRecovery": "重新生成恢复码",
  "securityOperationsNote": "高风险操作需要当前密码和新的动态验证码。修改密码或验证器后，网页会话与 OAuth 授权失效，需要重新登录；独立 Agent 密钥不随普通密码修改自动删除。",
  "sessions": "登录会话",
  "currentSession": "当前会话",
  "revokeOtherSessions": "退出其他会话",
  "reauthenticate": "再次验证身份",
  "currentPassword": "当前密码",
  "newPassword": "新密码",
  "otpFreshNote": "请使用尚未用于登录或其他操作的动态验证码；必要时等待下一组验证码。",
  "invitationLimits": "有效期 1–1440 分钟；本次最大生成数量：",
  "count": "生成数量",
  "ttlMinutes": "有效期（分钟）",
  "revokeBatch": "撤销整批",
  "operatorRequired": "当前账户不是平台管理员，不能访问注册码或其他账户的管理信息。",
  "role": "角色",
  "accountAdminNote": "只管理账户状态和角色，不提供访问其他用户记忆的入口。最后一位管理员受到保护。",
  "maintenanceRequired": "启停账户需要配置本地身份供应与凭证撤销 worker。",
  "enable": "启用",
  "disable": "停用",
  "grantOperator": "授予管理员",
  "revokeOperator": "移除管理员",
  "personalExport": "个人数据迁移",
  "importMemories": "导入个人记忆",
  "file": "导入文件",
  "portableNote": "导出本人原子记忆，不包含其他账户、凭证或整库文件。导入创建新的个人级记忆，不覆盖现有记录；非有效记录保留为撤回状态。来源历史与附件需使用离线完整备份。",
  "databaseRestoreNote": "共享数据库的整库恢复不能从个人控制台执行。运维需使用现有离线备份与隔离恢复命令，并在切换前校验。",
  "exportPrivacyNote": "下载文件包含你的记忆原文。请保存在私有位置，不要提交 GitHub。",
  "confirmImport": "我确认将文件内容导入为新的个人级记忆，不覆盖原记录",
  "importPartial": "已完成导入记录数",
  "operationId": "操作编号",
  "confirmAction": "确认执行此操作？",
  "consoleUpgradeRequired": "此账户仍使用只读核心凭证。请由运维显式升级控制台权限后使用写操作。",
  "recoveryNotConfigured": "网页恢复需要部署管理员配置证明组合与本地身份维护服务；未配置时不开放弱恢复入口。",
  "recoveryAction": "恢复项目",
  "resetPassword": "忘记密码",
  "resetTotp": "丢失验证器",
  "recoveryCode": "一次性恢复码",
  "recoveryProofNote": "重置密码：恢复码＋动态验证码。重置验证器：恢复码＋当前密码。仅填写所需证明；不输入 ChatGPT 密码。",
  "recoveryComplete": "凭证恢复已提交；身份供应完成后可重新登录。",
  "lexical": "字面检索",
  "hybrid": "混合检索",
  "semantic": "语义检索",
  "searchMode": "检索模式",
  "allStatuses": "全部状态",
  "CONSOLE_KEY_REQUIRED": "请先在服务器配置控制台加密密钥",
  "CONSOLE_UPGRADE_REQUIRED": "此账户的核心权限尚未升级",
  "REAUTHENTICATION_FAILED": "身份验证失败，请检查密码并使用新的动态验证码",
  "MEMORY_VERSION_CHANGED": "记忆已更新，请重新打开详情后操作",
  "MODEL_VERSION_CHANGED": "模型设置已更新，请重新打开配置",
  "NOT_CONFIGURED": "尚未启用所需模型",
  "EGRESS_DENIED": "模型外发尚未获准",
  "ADDRESS_DENIED": "目标地址被安全策略拒绝",
  "IDENTITY_MAINTENANCE_REQUIRED": "需要配置本地身份维护服务",
  "LAST_OPERATOR": "不能停用或降级最后一位管理员",
  "IDEMPOTENCY_CONFLICT": "此操作编号已用于不同请求",
  "OPERATION_PENDING": "操作结果尚未确认，请不要换编号重复提交",
  "IMPORT_CONTENT_TOO_LONG": "导入包含超过 4096 字符的记录，请使用离线迁移，未开始本次导入",
  "EDIT_REQUIRES_COMPLETE_RECORD": "超长记录需先完整读取并使用离线修订流程",
  "webVisibilityNote": "查看或修改 ChatGPT 对当前版本的读取许可",
  "memory.create": "新建记忆",
  "memory.correct": "修订记忆",
  "memory.retract": "撤回记忆",
  "memory.classify": "手动分类",
  "memory.sensitivity": "调整敏感级别",
  "memory.visibility": "ChatGPT 读取许可",
  "jobs.schedule": "提交整理任务",
  "jobs.retry": "重试任务",
  "jobs.cancel": "取消任务",
  "models.save": "保存模型设置",
  "models.disable": "停用模型",
  "models.test": "测试模型接口",
  "vector.schedule": "重建个人向量索引",
  "connections.create": "创建 Agent 连接",
  "connections.revoke": "撤销连接",
  "connections.rotate": "轮换连接密钥",
  "oauth.revoke": "撤销 OAuth 授权",
  "security.password": "修改账户密码",
  "security.totp.begin": "更换验证器",
  "security.totp.complete": "验证新验证器",
  "security.recovery_codes": "重新生成恢复码",
  "security.session.revoke": "退出指定会话",
  "security.sessions.revoke_others": "退出其他会话",
  "invitations.issue": "批量签发注册码",
  "invitations.revoke": "撤销注册码",
  "invitations.revoke_batch": "撤销批次",
  "accounts.disable": "停用账户",
  "accounts.enable": "启用账户",
  "accounts.role": "变更管理员角色",
  "storage.export": "导出我的记忆",
  "storage.import": "导入个人记忆"
});
Object.assign(catalog["en"],{
  "interactive": "Interactive",
  "actions": "Actions",
  "refresh": "Refresh",
  "save": "Save",
  "confirm": "Confirm",
  "content": "Memory content",
  "memoryType": "Memory type",
  "topic": "Topic (optional)",
  "scopeTarget": "Scope ID (blank for personal)",
  "user": "Personal",
  "project": "Project",
  "task": "Task",
  "workstream": "Workstream",
  "session": "Session",
  "fact": "Fact",
  "goal": "Goal",
  "constraint": "Constraint",
  "decision": "Decision",
  "completed": "Completed item",
  "blocker": "Blocker",
  "remaining": "Remaining work",
  "next_step": "Next step",
  "editMemory": "Correct memory",
  "retractMemory": "Retract memory",
  "classifyMemory": "Set category",
  "sensitivity": "Sensitivity",
  "webVisibility": "ChatGPT visibility",
  "reason": "Reason",
  "category": "Category",
  "sensitive": "Sensitive",
  "internal": "Internal",
  "public": "Public / egress allowed",
  "secret": "Secret (no egress)",
  "allowChatGPT": "Allow ChatGPT to read this revision",
  "grantRevisionNote": "Approval is pinned to this revision and expires on change. Secret records cannot be granted.",
  "sensitivityNote": "Changing sensitivity revokes the old grant and invalidates derived data. Public records need no individual grant.",
  "retractNote": "Retraction removes active recall while retaining content and history. No physical deletion.",
  "jobType": "Job type",
  "classification": "Classification",
  "summary": "Summary",
  "summarize": "Summarize",
  "timezone": "Time zone",
  "includeOpen": "Include the current open period",
  "enablePeriodic": "Enable periodic classification and daily/weekly summaries",
  "organizeCostNote": "A persistent worker executes this job. Approved model calls may send source text and incur costs. Missing configuration is not reported as success.",
  "scheduleStatus": "Scheduled organization",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "progress": "Progress",
  "cancelJob": "Cancel job",
  "vectorIndex": "Vector index",
  "organizer": "Organizer model",
  "embedder": "Embedding model",
  "testModel": "Test connection",
  "modelBoundary": "Model and data boundary",
  "modelBoundaryNote": "Models belong to this account. Keys are encrypted and never echoed. Egress requires approval; private-network services require operator configuration.",
  "vectorNotConfigured": "Qdrant is not configured. Configure the backend before rebuilding; lexical search remains available.",
  "rebuildIndex": "Rebuild my vector index",
  "hasKey": "Key stored",
  "yes": "Yes",
  "no": "No",
  "protocol": "API protocol",
  "baseUrl": "Model service URL",
  "modelName": "Model name",
  "modelRevision": "Model revision",
  "apiKey": "API key (blank keeps existing)",
  "removeKey": "Remove the stored key",
  "dimensions": "Vector dimensions",
  "dailyRequests": "Daily request ceiling",
  "outputTokens": "Output token limit",
  "batchSize": "Batch size",
  "modelSensitivity": "Highest allowed model sensitivity",
  "approveEgress": "I approve sending selected memory classes to this model",
  "approveQuery": "I also approve sending search queries for semantic retrieval",
  "keyWriteOnlyNote": "Keys are write-only. Changing the service origin clears the old key unless a new key is supplied.",
  "probeCostNote": "This sends synthetic text, not personal memories. The real model may charge and the call counts toward your daily limit.",
  "chatgptGrants": "ChatGPT grants",
  "agentConnections": "Agent connections",
  "mcpEndpoint": "MCP endpoint",
  "expires": "Expires",
  "addConnection": "Add connection",
  "label": "Connection name",
  "agentId": "Agent ID",
  "deviceId": "Device ID",
  "access": "Access",
  "read": "Read memories",
  "read_write": "Read and explicitly save",
  "rotateKey": "Rotate key",
  "revoked": "Revoked",
  "active": "Active",
  "managedConnection": "System / operator managed",
  "accountSecurity": "Account security actions",
  "changePassword": "Change password",
  "changeTotp": "Replace authenticator",
  "rotateRecovery": "Rotate recovery codes",
  "securityOperationsNote": "High-risk actions require the current password and a fresh OTP. Password/MFA changes invalidate browser sessions and OAuth grants. Standalone Agent keys are not deleted by ordinary password changes.",
  "sessions": "Login sessions",
  "currentSession": "Current session",
  "revokeOtherSessions": "Revoke other sessions",
  "reauthenticate": "Reauthenticate",
  "currentPassword": "Current password",
  "newPassword": "New password",
  "otpFreshNote": "Use an OTP not already consumed by login or another action. Wait for the next code when necessary.",
  "invitationLimits": "TTL: 1–1440 minutes. Maximum batch size:",
  "count": "Count",
  "ttlMinutes": "Lifetime (minutes)",
  "revokeBatch": "Revoke batch",
  "operatorRequired": "This account has no operator role. Invitation and account administration is unavailable.",
  "role": "Role",
  "accountAdminNote": "Manage account state and roles only, not other users’ memories. The last operator is protected.",
  "maintenanceRequired": "Account activation/suspension requires the local identity provisioning and revocation worker.",
  "enable": "Enable",
  "disable": "Disable",
  "grantOperator": "Grant operator",
  "revokeOperator": "Remove operator",
  "personalExport": "Personal data portability",
  "importMemories": "Import personal memories",
  "file": "Import file",
  "portableNote": "Exports your atomic memories, not other accounts, credentials or the database. Imports create new personal memories without overwriting records; non-active records remain retracted. Full provenance and attachments require an offline backup.",
  "databaseRestoreNote": "Shared-database restoration is an operator procedure, not a personal console action. Use the existing offline backup and isolated restore commands before switching.",
  "exportPrivacyNote": "The download contains memory text. Store it privately and never commit it to GitHub.",
  "confirmImport": "Import as new personal memories without overwriting originals",
  "importPartial": "Records imported before interruption",
  "operationId": "Operation ID",
  "confirmAction": "Confirm this operation?",
  "consoleUpgradeRequired": "This account still has a read-only Core credential. An operator must explicitly enable console write capabilities.",
  "recoveryNotConfigured": "Web recovery needs operator-configured proof combinations and local identity maintenance. No weak fallback is enabled.",
  "recoveryAction": "Recovery action",
  "resetPassword": "Reset password",
  "resetTotp": "Reset authenticator",
  "recoveryCode": "One-time recovery code",
  "recoveryProofNote": "Password reset: recovery code + OTP. Authenticator reset: recovery code + current password. Fill only the required factors, not your ChatGPT password.",
  "recoveryComplete": "Credentials recovered. Sign in after identity provisioning completes.",
  "lexical": "Lexical",
  "hybrid": "Hybrid",
  "semantic": "Semantic",
  "searchMode": "Search mode",
  "allStatuses": "All statuses",
  "CONSOLE_KEY_REQUIRED": "Configure the console encryption key on the server first",
  "CONSOLE_UPGRADE_REQUIRED": "This account’s Core permissions have not been upgraded",
  "REAUTHENTICATION_FAILED": "Reauthentication failed; check your password and use a fresh OTP",
  "MEMORY_VERSION_CHANGED": "Memory changed; reopen the detail before editing",
  "MODEL_VERSION_CHANGED": "Model settings changed; reopen configuration",
  "NOT_CONFIGURED": "The required model is not enabled",
  "EGRESS_DENIED": "Model egress has not been approved",
  "ADDRESS_DENIED": "The destination address is denied by security policy",
  "IDENTITY_MAINTENANCE_REQUIRED": "Local identity maintenance must be configured",
  "LAST_OPERATOR": "The last operator cannot be disabled or demoted",
  "IDEMPOTENCY_CONFLICT": "This operation ID belongs to another request",
  "OPERATION_PENDING": "Operation outcome is pending; do not resubmit with a new ID",
  "IMPORT_CONTENT_TOO_LONG": "A record exceeds 4096 characters. Use offline migration; this import has not started",
  "EDIT_REQUIRES_COMPLETE_RECORD": "Read the full oversized record and use offline correction",
  "webVisibilityNote": "Inspect or change ChatGPT access to the current revision",
  "memory.create": "Create memory",
  "memory.correct": "Correct memory",
  "memory.retract": "Retract memory",
  "memory.classify": "Classify memory",
  "memory.sensitivity": "Change sensitivity",
  "memory.visibility": "ChatGPT access",
  "jobs.schedule": "Schedule organization",
  "jobs.retry": "Retry job",
  "jobs.cancel": "Cancel job",
  "models.save": "Save model settings",
  "models.disable": "Disable model",
  "models.test": "Test model API",
  "vector.schedule": "Rebuild personal vector index",
  "connections.create": "Create Agent connection",
  "connections.revoke": "Revoke connection",
  "connections.rotate": "Rotate connection key",
  "oauth.revoke": "Revoke OAuth grant",
  "security.password": "Change account password",
  "security.totp.begin": "Replace authenticator",
  "security.totp.complete": "Verify new authenticator",
  "security.recovery_codes": "Rotate recovery codes",
  "security.session.revoke": "Revoke session",
  "security.sessions.revoke_others": "Revoke other sessions",
  "invitations.issue": "Issue invitation codes",
  "invitations.revoke": "Revoke invitation",
  "invitations.revoke_batch": "Revoke invitation batch",
  "accounts.disable": "Disable account",
  "accounts.enable": "Enable account",
  "accounts.role": "Change operator role",
  "storage.export": "Export my memories",
  "storage.import": "Import personal memories"
});

Object.assign(catalog['zh-CN'],{modelNotConfigured:'尚未配置',nativeSchema:'服务支持原生 JSON Schema',searchMode:'检索方式',lexical:'精确检索',hybrid:'混合检索',semantic:'语义检索',workerStatus:'后台执行器',workerDisabledNote:'任务已持久保存。管理员需要启用后台执行器，任务才会运行。'});
Object.assign(catalog.en,{modelNotConfigured:'Not configured',nativeSchema:'Service supports native JSON Schema',searchMode:'Search mode',lexical:'Lexical',hybrid:'Hybrid',semantic:'Semantic',workerStatus:'Worker',workerDisabledNote:'Jobs are stored durably. An operator must enable the worker before queued jobs can run.'});

Object.assign(catalog['zh-CN'],{CSRF_REFRESH_REQUIRED:'表单校验已更新，请重新确认本次操作',EXPORT_SIZE_LIMIT:'导出超过 16 MiB，请使用运维备份或分批导出',BUDGET_EXHAUSTED:'今日模型调用额度已用尽',WEB_VISIBILITY_DENIED:'此分类或版本不允许授权；secret 不会发送给 ChatGPT',CONSOLE_REQUEST_FAILED:'操作未完成，请核对输入和服务状态',MODEL_URL_DENIED:'服务地址不符合网络安全策略'});
Object.assign(catalog.en,{CSRF_REFRESH_REQUIRED:'Form protection refreshed; confirm this operation again',EXPORT_SIZE_LIMIT:'Export exceeds 16 MiB; use operator backup or split exports',BUDGET_EXHAUSTED:'Daily model-call limit reached',WEB_VISIBILITY_DENIED:'This class or revision cannot be granted; secret is never sent to ChatGPT',CONSOLE_REQUEST_FAILED:'Operation did not complete; check input and service state',MODEL_URL_DENIED:'Service URL is denied by network policy'});

export const text=(key,locale='zh-CN')=>catalog[locale]?.[key]??catalog.en[key]??key;
