export const catalog={
 'zh-CN':{
  consoleLogin:'登录管理控制台',consoleLoginNote:'管理自己的记忆和连接。此登录不会自动向 ChatGPT 授权。',oauthLogin:'连接 ChatGPT',oauthLoginNote:'先验证你的 Mnemuron 账户，再明确允许只读访问。这不会登录管理控制台。',oauthConsent:'允许 ChatGPT 只读访问',oauthRestartHelp:'此链接只用于本次授权，并非固定的集成页面。请关闭此页，回到 ChatGPT 重新发起连接。',oauthRetry:'重试本次授权',
  overview:'概览',memories:'记忆库',summaries:'分类与摘要',jobs:'整理任务',connections:'连接管理',models:'模型配置',security:'账户安全',audit:'审计记录',storage:'存储与备份',invitations:'注册码管理',accounts:'账户管理',
  workspace:'我的空间',settings:'连接与设置',platform:'平台管理 · 权限待定',brandNote:'个人记忆，持续连接。',hero:'你的记忆，井然有序。',heroNote:'保留每条信息的来源，让上下文在会话间延续。',
  login:'登录 Mnemuron',register:'创建你的账户',recover:'账户恢复',username:'用户名',password:'密码',otp:'动态验证码',invitation:'一次性注册码',continue:'继续',signIn:'登录',signOut:'退出当前会话',cancel:'取消',allow:'允许只读访问',
  scopeMemoryWrite:'按你的明确要求保存、版本化修订或撤回记忆',allowMemoryWrite:'允许记忆读写',consentWriteNote:'仅可保存你提交的记忆，以及修订或撤回属于你且网页可见的记忆。不切换任务、不确认 Resume、不调度模型或执行管理操作。',consentSubmittedGrant:'每次提交新版本时须明确选择保持私有，或允许本账户具有读取权限的云端连接读取该版本（不限当前连接）。不会开放旧记录。',consentPrivateOnly:'本次提交的新版本保持私有，云端仅获得不含正文的保存回执。',
  authNote:'请使用 Mnemuron 账户，不要输入 ChatGPT 密码。',inviteNote:'注册码由服务器管理员签发，仅可使用一次。',totp:'绑定验证器',totpNote:'使用验证器扫描二维码，或手动输入密钥。密钥只在绑定期间可见。',verify:'验证并继续',copy:'复制',copied:'已复制',showPassword:'显示密码',hidePassword:'隐藏密码',
  recoveryCodes:'保存恢复码',recoveryNote:'这些恢复码仅显示一次。请离线保存，不要上传或分享。',acknowledge:'我已保存恢复码',pending:'正在等待安全绑定',pendingNote:'MFA 已验证。核心身份供应与恢复码确认全部完成后才能登录。',registered:'注册完成，请正常登录',
  blocked:'策略待确认',blockedNote:'此操作尚未获准。页面展示不代表操作已开放。',unavailable:'暂不可用',retry:'重试',loading:'正在加载…',empty:'目前没有可显示的记录',noConnection:'尚无已授权连接',authenticated:'已验证账户',restartAuthorization:'账户或授权会话已变化。请返回请求连接的应用，重新发起授权。',
  search:'搜索记忆',query:'搜索内容',readOnly:'只读',memoryCount:'原子记忆',sourceCount:'来源记录',summaryCount:'摘要',jobCount:'整理任务',recent:'最近的记忆',viewAll:'查看全部',detail:'记忆详情',sources:'来源',revisions:'版本',next:'下一页',previous:'上一页',close:'关闭',complete:'内容已完整读取',changed:'来源或版本已变化，请重新读取。',
  language:'语言',
  securityNote:'登录需要密码与动态验证码。恢复证明组合尚待确认，不启用弱恢复。',modelsNote:'模型资源与费用策略待确认。不显示密钥或其他账户配置。',storageNote:'只展示本人记录的统计。整库备份、恢复与下载不在网页权限内。',platformNote:'当前账户没有平台管理授权。此页不返回其他账户的身份或统计。',
  error:'请求未完成',errorNote:'请返回并重试。未授权、过期或依赖故障不会跳过安全校验。',identity:'当前账户',state:'状态',created:'创建时间',scope:'范围',status:'状态',consent:'授权连接',consentNote:'仅允许读取你授权的记忆和项目。不会写入记忆、切换任务或确认 Resume。',
  policy:'权限边界',pendingPolicies:'未批准操作保持关闭',noDemo:'所有数据来自当前账户；不可用时不会显示演示数据。',newMemory:'新建记忆',organize:'手动整理',export:'导出记忆',restore:'整库恢复',configure:'修改配置',issue:'网页签发',manage:'角色管理',revoke:'撤销授权',
  passwordConfirm:'再次输入密码',alreadyShown:'密钥已显示过。本页不会重新展示；请使用已保存的验证器或恢复码。',oauthClient:'请求连接的应用',scopeIdentity:'识别你的 Mnemuron 账户',scopeOffline:'使用可撤销、轮换的刷新令牌保持连接',scopeMemory:'读取你授权的记忆',scopeProject:'读取你授权的项目上下文',systemLabel:'个人记忆系统',workspaceLabel:'个人工作空间',heroLabel:'让记忆持续连接',passwordTotp:'密码与动态验证码',back:'返回安全入口',expired:'此步骤已过期，请从安全入口重新开始。',loginFailed:'登录信息无效或账户尚不可用。请检查凭证后重试。',rateLimited:'尝试过于频繁，请稍后重试。',pendingStep:'此步骤暂不可用，请重新检查当前注册状态。',
 },
 en:{
  consoleLogin:'Sign in to the console',consoleLoginNote:'Manage your memories and connections. This sign-in does not authorize ChatGPT.',oauthLogin:'Connect ChatGPT',oauthLoginNote:'Verify your Mnemuron account, then explicitly allow read-only access. This does not sign you in to the console.',oauthConsent:'Allow ChatGPT read-only access',oauthRestartHelp:'This link belongs to one authorization request, not a permanent integration page. Close this page and start a new connection from ChatGPT.',oauthRetry:'Retry this authorization',
  overview:'Overview',memories:'Memory library',summaries:'Categories & summaries',jobs:'Organizer jobs',connections:'Connections',models:'Model settings',security:'Account security',audit:'Audit log',storage:'Storage & backup',invitations:'Registration codes',accounts:'Accounts',
  workspace:'My workspace',settings:'Connections & settings',platform:'Platform · policy pending',brandNote:'Personal memory. Lasting context.',hero:'Your memory, thoughtfully organized.',heroNote:'Keep the provenance of every detail. Carry context across conversations.',
  login:'Sign in to Mnemuron',register:'Create your account',recover:'Account recovery',username:'Username',password:'Password',otp:'Authenticator code',invitation:'One-time registration code',continue:'Continue',signIn:'Sign in',signOut:'Sign out of this session',cancel:'Cancel',allow:'Allow read-only access',
  scopeMemoryWrite:'Save, version-correct or retract memories on your explicit request',allowMemoryWrite:'Allow memory read and write',consentWriteNote:'Save submitted memories; correct or retract only your owned, Web-visible memories. No task switching, Resume, model scheduling or administration.',consentSubmittedGrant:'Explicitly choose private or readable for each newly submitted version. Readable means accessible to this account\'s authorized cloud readers, not only this connection. Existing records are never granted.',consentPrivateOnly:'New submitted versions remain private. The cloud receives a metadata-only receipt without the body.',
  authNote:'Use your Mnemuron account, not your ChatGPT password.',inviteNote:'Registration codes are issued by your operator and can only be used once.',totp:'Connect your authenticator',totpNote:'Scan the QR code or enter the key manually. The key is available only during enrollment.',verify:'Verify and continue',copy:'Copy',copied:'Copied',showPassword:'Show password',hidePassword:'Hide password',
  recoveryCodes:'Save your recovery codes',recoveryNote:'These codes are shown once. Store them offline. Do not upload or share them.',acknowledge:'I have saved my recovery codes',pending:'Waiting for secure identity binding',pendingNote:'MFA is verified. Login requires completed Core provisioning and recovery-code acknowledgement.',registered:'Registration complete. Please sign in.',
  blocked:'Policy pending',blockedNote:'This operation has not been approved. Visibility does not grant permission.',unavailable:'Currently unavailable',retry:'Retry',loading:'Loading…',empty:'No records to display yet',noConnection:'No authorized connection yet',authenticated:'Verified account',restartAuthorization:'The account or authorization session changed. Return to the requesting application and start a new authorization.',
  search:'Search memories',query:'Search query',readOnly:'Read-only',memoryCount:'Atomic memories',sourceCount:'Source records',summaryCount:'Summaries',jobCount:'Organizer jobs',recent:'Recent memories',viewAll:'View all',detail:'Memory detail',sources:'Sources',revisions:'Revision',next:'Next page',previous:'Previous page',close:'Close',complete:'Complete content returned',changed:'The source or revision changed. Read it again.',
  language:'Language',
  securityNote:'Sign-in requires a password and authenticator code. Recovery proof policy is pending; no weaker recovery is enabled.',modelsNote:'Model resources and cost policy are pending. Keys and other accounts’ configuration are never shown.',storageNote:'Only your record totals are shown. Whole-database backup, restore and download are not web capabilities.',platformNote:'This account has no platform management grant. This page returns no other account identities or statistics.',
  error:'Request not completed',errorNote:'Go back and try again. Authorization, expiry and dependency checks are never bypassed.',identity:'Current account',state:'State',created:'Created',scope:'Scope',status:'Status',consent:'Authorize connection',consentNote:'Read only memories and projects you authorize. No memory writes, task switching or Resume confirmation.',
  policy:'Permission boundary',pendingPolicies:'Unapproved operations stay disabled',noDemo:'All data belongs to the current account. No demo fallback when unavailable.',newMemory:'New memory',organize:'Run organizer',export:'Export memories',restore:'Restore database',configure:'Change settings',issue:'Issue in browser',manage:'Manage roles',revoke:'Revoke grant',
  passwordConfirm:'Confirm password',alreadyShown:'The secret was already displayed. It is not shown again; use your saved authenticator or recovery codes.',oauthClient:'Application requesting access',scopeIdentity:'Identify your Mnemuron account',scopeOffline:'Keep this connection with revocable, rotating refresh tokens',scopeMemory:'Read memories you authorize',scopeProject:'Read project context you authorize',systemLabel:'PERSONAL MEMORY SYSTEM',workspaceLabel:'PERSONAL WORKSPACE',heroLabel:'YOUR MEMORY, CONNECTED',passwordTotp:'Password and authenticator code',back:'Return to the safe entry point',expired:'This step expired. Start again from the safe entry point.',loginFailed:'The sign-in details or account are unavailable. Check your credentials and try again.',rateLimited:'Too many attempts. Please try again later.',pendingStep:'This step is unavailable. Check your current registration status.',
 }
};

Object.assign(catalog['zh-CN'],{
 connRevokeGrant:'仅撤销本次授权',connRevokeGrantNote:'只撤销选中的授权及其令牌，不撤销整个连接或其他授权；需要时可重新登录授权。',
 connIntro:'为自己的云端应用创建独立连接，分别控制访问权限与凭证。',connHealthNote:'配置完成不等于已连通；只有真实记忆工具调用成功后才显示“已验证”。',connActive:'当前连接',connReadWrite:'记忆读写',connPending:'待完成配置',connChatGPT:'ChatGPT Web',connGeneric:'通用 MCP 客户端',connAgent:'其他 Agent',connAll:'全部',connSearch:'搜索连接名称',connType:'连接类型',connSection:'查看范围',connCurrent:'当前连接',connHistory:'撤销与过期历史',connFilteredCount:'符合筛选的连接',connConfigure:'查看与配置',connEmpty:'尚无匹配连接，可新建连接或调整筛选。',connPolicy:'连接签发尚未启用；不会生成凭证。',connSystem:'系统与历史连接',connSystemNote:'以下是系统管理凭证或旧授权，不代表独立设备，不计入上方用户连接统计。',connLegacy:'旧版 ChatGPT 连接',connLegacyNote:'保留原有授权和权限；不会自动升级为读写连接。',connUnmatchedHistory:'未匹配的历史授权',connUnmatchedNote:'无法可靠归并到当前连接，因此仅展示历史元数据。',connChooseType:'选择要连接的应用',connChatGPTNote:'生成专用 OAuth 客户端，再填写 ChatGPT 提供的精确回调地址。',connGenericNote:'使用有限期个人令牌。客户端必须支持 Streamable HTTP 与自定义 Authorization 标头。',connAgentNote:'暂未实现专用接入，不能创建虚假连接。',connDescription:'用途说明（可选）',connVersionGrant:'允许此连接在每次提交时显式请求新版本云端可读',connPrivacyNote:'不会开放旧记忆。新版本只有在工具提交时再次明确选择，才向同账户具有读取权限的云端连接开放。',connTokenDays:'令牌有效天数',connClientLifetime:'OAuth Client Secret 持续有效，直至主动轮换或撤销；它不是短期访问令牌。',connBack:'上一步',connGenerateNote:'请输入当前密码和新的动态验证码。生成后请立即安全保存凭证。',connGenerate:'生成凭证',connSecretNote:'凭证仅在本次登录内最多恢复 5 分钟。请手动复制到目标客户端，不要发送到聊天或工单。',connClientId:'OAuth Client ID',connUntilRevoked:'直到轮换或撤销',connSecret:'私密凭证',connCopySecret:'复制私密凭证',connSavedContinue:'我已保存，继续配置',connSecretExpired:'凭证展示已过期；如未保存，请重新轮换生成。',connDiscardSecret:'凭证尚未确认保存。关闭后将清除本页凭证，确定关闭？',connGuide:'接入步骤',connTransport:'传输方式',connCopyUrl:'复制服务地址',connCopyParams:'复制参数模板',connCopyId:'复制连接 ID',connOAuthSteps:'1. 在 ChatGPT 创建自定义 MCP 连接并选择 OAuth。2. 填写 Client ID、已保存的 Secret 和 client_secret_post。3. 将 ChatGPT 显示的完整回调地址复制到本连接配置。4. 等待身份供应后，在 ChatGPT 登录并明确授权；再实际搜索或读取记忆。',connGenericSteps:'将服务地址与个人令牌填入支持自定义标头的 MCP 客户端：Authorization: Bearer <令牌>。复制的模板只是中性参数清单，不是所有客户端都能导入的配置文件。',connCallback:'精确回调地址',connCallbackMissing:'尚未填写，请从 ChatGPT 配置页复制',connCredentials:'凭证与授权',connRotateNote:'修改权限或配置、轮换后，旧会话和令牌立即失效；需重新连接。系统会安全供应新的核心身份。',connRevokeNote:'撤销后此连接不能恢复；旧令牌与刷新令牌立即失效。不删除记忆。',connDisableNote:'停用会立即阻止此连接访问；重新启用时将生成新凭证。不影响其他连接。',connGrantCount:'授权记录（最多 50 条）',connKeyCount:'令牌记录（最多 50 条）',connActivity:'近期活动（最多 50 条）',connNoActivity:'尚无活动',connExpired:'已过期',connState_draft:'待配置',connState_ready:'配置完成',connState_disabled:'已停用',connState_revoked:'已撤销',connHealth_never_used:'尚未验证',connHealth_authorized:'已完成授权',connHealth_verified:'记忆调用已验证',connHealth_unknown:'状态未知',connAction_update:'修改配置',connAction_rotate:'轮换凭证',connAction_disable:'停用',connAction_enable:'重新启用',connAction_revoke:'撤销连接',oauthWriteLoginNote:'先验证你的 Mnemuron 账户，再明确允许本次请求的记忆读写权限。此步骤不会登录管理控制台。',
 CONNECTION_QUOTA:'已达到本账户连接数量上限，请先撤销不再使用的连接。',CONNECTION_NOT_FOUND:'此连接不存在或不属于当前账户。',CONNECTION_REVOKED:'连接已撤销，不能继续修改。',INVALID_CALLBACK:'回调地址不被允许；请完整复制 ChatGPT 显示的 HTTPS 回调地址，不使用通配符。',INVALID_CONNECTION_INPUT:'连接配置不完整或含不允许的参数。',INVALID_TOKEN_LIFETIME:'令牌有效期超出允许范围。',CONNECTION_POLICY_REQUIRED:'连接管理尚未启用。',SECRET_SESSION_MISMATCH:'凭证只能在原登录中恢复；请刷新列表，必要时轮换。',CLOUD_WRITE_NOT_ENABLED:'此连接未启用云端记忆写入。',CLOUD_READ_POLICY_DENIED:'当前连接不允许授予本次版本云端读取权限。',
 connHealth_degraded:'最近记忆调用失败',connAuthUrl:'授权地址',connTokenUrl:'令牌地址',connTokenAuth:'令牌端点认证',connResource:'资源标识',connTimeout:'建议客户端超时（秒）',connToolList:'可用工具',connTroubleshooting:'修改权限后需要重新授权并刷新客户端工具列表。401 表示凭证失效，403 表示权限或身份绑定不满足；待配置时先检查回调和身份供应。不要把账户密码或动态口令放入 MCP 配置。',
 'connections.create':'创建连接','connections.update':'修改配置','connections.rotate':'轮换凭证','connections.disable':'停用连接','connections.enable':'重新启用','connections.revoke':'撤销连接','connection.authorized':'完成 OAuth 授权','connection.tool_succeeded':'记忆工具调用成功','connection.tool_failed':'记忆工具调用失败','connection.binding_ready':'身份绑定完成',success:'成功',failed:'失败'
});
Object.assign(catalog.en,{
 connRevokeGrant:'Revoke this grant only',connRevokeGrantNote:'Revokes only the selected grant and its tokens, not the connection or other grants. You can authorize again.',
 connIntro:'Create separate connections for your cloud applications, each with its own permissions and credentials.',connHealthNote:'Configured is not verified. Only a successful real memory tool call verifies a connection.',connActive:'Current connections',connReadWrite:'Memory read & write',connPending:'Setup pending',connChatGPT:'ChatGPT Web',connGeneric:'Generic MCP client',connAgent:'Other Agent',connAll:'All',connSearch:'Search connection name',connType:'Connection type',connSection:'View',connCurrent:'Current',connHistory:'Revoked & expired',connFilteredCount:'Matching connections',connConfigure:'View & configure',connEmpty:'No matching connections. Create one or change the filters.',connPolicy:'Connection issuance is not enabled. No credentials will be generated.',connSystem:'System & historical connections',connSystemNote:'Managed credentials and old grants below are not independent devices and are not counted above.',connLegacy:'Legacy ChatGPT connection',connLegacyNote:'Existing grants and permissions are preserved, never automatically upgraded to read & write.',connUnmatchedHistory:'Unmatched historical grants',connUnmatchedNote:'These grants cannot reliably be assigned to a current connection; only historical metadata is shown.',connChooseType:'Choose an application',connChatGPTNote:'Create a dedicated OAuth client, then copy the exact callback from ChatGPT.',connGenericNote:'Use a finite personal token. The client must support Streamable HTTP and custom Authorization headers.',connAgentNote:'Dedicated integration is not implemented. No simulated connection can be created.',connDescription:'Purpose (optional)',connVersionGrant:'Allow explicit requests to make each newly submitted revision cloud-readable',connPrivacyNote:'Existing memories are never opened. Each submission must separately opt in; that revision is readable by authorized cloud readers of the same account.',connTokenDays:'Token lifetime in days',connClientLifetime:'The OAuth Client Secret remains valid until rotated or revoked. It is not a short-lived access token.',connBack:'Back',connGenerateNote:'Enter your current password and a fresh authenticator code. Securely save the generated credential.',connGenerate:'Generate credential',connSecretNote:'Recoverable for at most 5 minutes in this login only. Copy manually to the target client; never send it to chats or tickets.',connClientId:'OAuth Client ID',connUntilRevoked:'Until rotation or revocation',connSecret:'Private credential',connCopySecret:'Copy private credential',connSavedContinue:'Saved; continue setup',connSecretExpired:'Secret display expired. Rotate if you did not save it.',connDiscardSecret:'You have not confirmed saving this credential. Close and clear it from this page?',connGuide:'Connection guide',connTransport:'Transport',connCopyUrl:'Copy service URL',connCopyParams:'Copy parameter template',connCopyId:'Copy connection ID',connOAuthSteps:'1. Create a custom MCP connection in ChatGPT and select OAuth. 2. Enter Client ID, your saved Secret and client_secret_post. 3. Copy the full ChatGPT callback into this connection. 4. Wait for identity provisioning, sign in and explicitly authorize in ChatGPT, then search or read a memory.',connGenericSteps:'Configure the URL and personal token in a client that supports custom headers: Authorization: Bearer <token>. The copied template is a neutral parameter list, not a universally importable client configuration.',connCallback:'Exact callback URL',connCallbackMissing:'Not set; copy from ChatGPT connection settings',connCredentials:'Credentials & grants',connRotateNote:'Changing permissions or configuration, or rotating, immediately invalidates old grants and tokens. Reconnect after secure identity provisioning.',connRevokeNote:'Revocation is permanent for this connection. Existing tokens and refresh tokens immediately stop working. Memories are not deleted.',connDisableNote:'Disabling immediately blocks this connection. Enabling generates new credentials. Other connections are unaffected.',connGrantCount:'Grants (up to 50)',connKeyCount:'Tokens (up to 50)',connActivity:'Recent activity (up to 50)',connNoActivity:'No activity yet',connExpired:'Expired',connState_draft:'Setup needed',connState_ready:'Configured',connState_disabled:'Disabled',connState_revoked:'Revoked',connHealth_never_used:'Not yet verified',connHealth_authorized:'Authorized',connHealth_verified:'Memory call verified',connHealth_unknown:'Unknown',connAction_update:'Configure',connAction_rotate:'Rotate credential',connAction_disable:'Disable',connAction_enable:'Enable again',connAction_revoke:'Revoke connection',oauthWriteLoginNote:'Verify your Mnemuron account, then explicitly approve the requested memory read/write access. This does not sign you in to the console.',
 CONNECTION_QUOTA:'Your connection quota is reached. Revoke an unused connection first.',CONNECTION_NOT_FOUND:'This connection is missing or not owned by this account.',CONNECTION_REVOKED:'The connection is revoked and cannot be changed.',INVALID_CALLBACK:'Copy the full HTTPS callback shown by ChatGPT. Wildcards are not allowed.',INVALID_CONNECTION_INPUT:'Connection settings are incomplete or contain unsupported fields.',INVALID_TOKEN_LIFETIME:'The token lifetime is outside the allowed range.',CONNECTION_POLICY_REQUIRED:'Connection management is not enabled.',SECRET_SESSION_MISMATCH:'The credential can only be recovered in the original login. Refresh and rotate if needed.',CLOUD_WRITE_NOT_ENABLED:'Cloud memory writes are not enabled for this connection.',CLOUD_READ_POLICY_DENIED:'This connection cannot grant cloud access to a submitted revision.',
 connHealth_degraded:'Last memory call failed',connAuthUrl:'Authorization URL',connTokenUrl:'Token URL',connTokenAuth:'Token endpoint authentication',connResource:'Resource identifier',connTimeout:'Suggested client timeout (seconds)',connToolList:'Available tools',connTroubleshooting:'After permission changes, authorize again and refresh the client tool list. 401 means invalid credentials; 403 means insufficient permission or identity binding. For pending setup, check the callback and identity provisioning. Never put account passwords or authenticator codes in MCP settings.',
 'connections.create':'Connection created','connections.update':'Configuration updated','connections.rotate':'Credential rotated','connections.disable':'Connection disabled','connections.enable':'Connection enabled','connections.revoke':'Connection revoked','connection.authorized':'OAuth authorization completed','connection.tool_succeeded':'Memory tool call succeeded','connection.tool_failed':'Memory tool call failed','connection.binding_ready':'Identity binding ready',success:'Succeeded',failed:'Failed'
});

// Presentation copy is separate from backend status codes and never translates memory content.
Object.assign(catalog['zh-CN'], {
  viewWithoutWrite:'可以查看详情；修改操作尚未启用。不会因为点击查看而改变数据。',
  inspectDetails:'查看详情',uncategorized:'未分类',preferences:'偏好',projects:'项目',technical:'技术',personal:'个人',decisions:'决策',superseded:'已被修订',retracted:'已撤回',
  technicalDetails:'技术详情',protocol:'接口协议',updated:'更新时间',lastUsed:'最后使用',agentInstance:'Agent 实例',sessionIdentifier:'会话标识',processedCount:'已处理',attemptCount:'尝试次数',resultReference:'结果标识',
  previousRecord:'查看修订前记忆',replacementRecord:'查看后续修订',summaryNotCurrent:'此摘要已失效，不能作为当前结论；可查看相关原始记忆。',current:'当前',stale:'已失效',
  allCategories:'全部分类',category:'分类',resetFilters:'清除筛选',inspectSourcesNote:'请选择一条记忆，展开详情中的来源；不会载入原始事件正文。',
  boundedSearchNote:'检索结果受候选窗口限制；请缩小关键词或筛选范围，不代表已列出全部记忆',
  capabilitiesUnavailable:'权限信息暂时无法读取，修改操作已关闭；仍可尝试查看本人数据。',
  contentRange:'本页字符',endOfContent:'已到正文末尾',sourceMetadata:'查看来源信息',nextSources:'下一页来源',
  connectionHeadline:'ChatGPT，接上你的个人记忆。', connectionDescription:'从已授权的记忆中找回上下文。来源、版本与访问范围，始终清晰可查。',
  manageConnections:'管理我的连接', browseMemories:'浏览记忆', ownedRecords:'仅当前账户', recentLabel:'近期记忆', processingLabel:'整理概况',
  memoryProcessing:'记忆整理', atomicNote:'保留原文与版本', derivedNote:'来源关联的派生视图', jobStatusNote:'进入任务页查看执行状态',
  summaryBoundary:'摘要是派生视图，不覆盖原文。遗漏与待核实信息保留在来源中。', viewJobs:'查看整理任务', inspectMemoryNote:'点开任意记忆，查看正文、来源与修订历史。',
  authHeadlineFirst:'记住重要的。', authHeadlineSecond:'只属于你的。', authDescription:'用一个独立空间连接你的记忆，让每次对话从理解开始。',
  authEyebrow:'连接到你的记忆空间', accountMenu:'当前账户与退出', authFooter:'Mnemuron · 个人记忆，持续上下文',
  pageNote_memories:'搜索、查看并追溯属于你的每一条记忆。', pageNote_summaries:'分类整理与来源关联的摘要，始终与原始记忆分开。',
  pageNote_jobs:'查看整理任务的进度、结果与需要处理的问题。', pageNote_connections:'在同一处查看你的应用授权和 Agent 连接。',
  pageNote_models:'查看模型配置边界与外发政策。密钥不会在页面回显。', pageNote_security:'管理你的身份、验证器与账户访问。',
  pageNote_audit:'仅查看当前账户的访问与安全事件。', pageNote_storage:'了解个人记录与存储边界。个人数据不等于整库备份。',
  pageNote_invitations:'查看注册准入规则。签发能力由明确的运维权限控制。',
  pageNote_accounts:'账户管理与个人记忆读取相互独立。',
});
Object.assign(catalog.en, {
  viewWithoutWrite:'Details are available. Changes are not enabled; inspecting data will not modify it.',
  inspectDetails:'Inspect details',uncategorized:'Uncategorized',preferences:'Preferences',projects:'Projects',technical:'Technical',personal:'Personal',decisions:'Decisions',superseded:'Superseded',retracted:'Retracted',
  technicalDetails:'Technical details',protocol:'Protocol',updated:'Updated',lastUsed:'Last used',agentInstance:'Agent instance',sessionIdentifier:'Session ID',processedCount:'Processed',attemptCount:'Attempts',resultReference:'Result reference',
  previousRecord:'Read previous memory',replacementRecord:'Read replacement memory',summaryNotCurrent:'This summary is no longer current. Inspect the related original memories instead.',current:'Current',stale:'Stale',
  allCategories:'All categories',category:'Category',resetFilters:'Clear filters',inspectSourcesNote:'Open a memory and expand its sources. Raw event bodies are not loaded.',
  boundedSearchNote:'Search is limited to a candidate window. Narrow the query or filters; this is not an exhaustive memory listing',
  capabilitiesUnavailable:'Permissions could not be loaded. Changes are disabled; you can still try viewing your data.',
  contentRange:'Characters on this page',endOfContent:'End of content',sourceMetadata:'Inspect provenance',nextSources:'Next source page',
  connectionHeadline:'Connect ChatGPT to your personal memory.', connectionDescription:'Find context in memories you authorize. Keep every source, revision and access boundary in view.',
  manageConnections:'Manage my connections', browseMemories:'Browse memories', ownedRecords:'This account only', recentLabel:'RECENT MEMORIES', processingLabel:'PROCESSING',
  memoryProcessing:'Memory organization', atomicNote:'Originals and revisions retained', derivedNote:'Source-linked derived views', jobStatusNote:'Open jobs for execution status',
  summaryBoundary:'Summaries are derived views, not replacements for originals. Check sources for omissions and uncertainty.', viewJobs:'View organizer jobs', inspectMemoryNote:'Open a memory to inspect its content, provenance and revision history.',
  authHeadlineFirst:'Remember what matters.', authHeadlineSecond:'Keep it yours.', authDescription:'An independent space for your memories. Start every conversation with context.',
  authEyebrow:'CONNECT TO YOUR MEMORY', accountMenu:'Current account and sign out', authFooter:'Mnemuron · Personal memory, continuous context',
  pageNote_memories:'Search, inspect and trace every memory in your own space.', pageNote_summaries:'Source-linked categories and summaries, kept separate from original memories.',
  pageNote_jobs:'Inspect organizer progress, results and items that need attention.', pageNote_connections:'Review your application grants and Agent connections in one place.',
  pageNote_models:'Review model boundaries and egress policy. Secret keys are never displayed.', pageNote_security:'Your identity, authenticator and account access.',
  pageNote_audit:'Access and security events for the current account only.', pageNote_storage:'Understand your record totals. Personal data is not a whole-database backup.',
  pageNote_invitations:'Review registration rules. Issuance requires explicit operator permission.',
  pageNote_accounts:'Account administration does not grant access to personal memories.',
});

Object.assign(catalog["zh-CN"],{
  "interactive": "可操作",
  "actions": "操作",
  "refresh": "刷新",
  "save": "保存",
  "confirm": "确认执行",
  "content": "记忆内容",
  "memoryType": "记忆类型",
  "topic": "主题（可选）",
  "scopeTarget": "范围 ID（个人级留空）",
  "user": "个人",
  "project": "项目",
  "task": "任务",
  "workstream": "工作分支",
  "session": "会话",
  "fact": "事实",
  "goal": "目标",
  "constraint": "约束",
  "decision": "决定",
  "completed": "已完成事项",
  "blocker": "阻碍",
  "remaining": "剩余事项",
  "next_step": "下一步",
  "editMemory": "修订记忆",
  "retractMemory": "撤回记忆",
  "classifyMemory": "手动分类",
  "sensitivity": "敏感级别",
  "webVisibility": "ChatGPT 可见性",
  "reason": "变更原因",
  "category": "分类",
  "sensitive": "敏感",
  "internal": "内部",
  "public": "公开可外发",
  "secret": "机密（不外发）",
  "allowChatGPT": "允许 ChatGPT 读取当前版本",
  "grantRevisionNote": "授权仅适用于当前版本。修订后自动失效；机密记录不能授权外发。",
  "sensitivityNote": "更改分类会撤销旧的 ChatGPT 授权，并使相关摘要和索引失效。公开记录无需单独授权。",
  "retractNote": "撤回后不再作为有效记忆检索；原文和历史保留，不物理删除。",
  "jobType": "整理类型",
  "classification": "自动分类",
  "summary": "生成摘要",
  "summarize": "生成摘要",
  "timezone": "时区",
  "includeOpen": "本次包含尚未结束的周期",
  "enablePeriodic": "启用定期分类与每日／每周汇总",
  "organizeCostNote": "任务交给后台 worker 执行，可能向已批准的模型发送选中范围内的原文并产生费用。未配置模型时不会伪报完成。",
  "scheduleStatus": "周期整理",
  "enabled": "已启用",
  "disabled": "已关闭",
  "progress": "处理进度",
  "cancelJob": "取消任务",
  "vectorIndex": "向量索引",
  "organizer": "分类与摘要模型",
  "embedder": "向量模型",
  "testModel": "测试连接",
  "modelBoundary": "模型与数据边界",
  "modelBoundaryNote": "模型配置只属于当前账户。密钥加密保存且不回显。外发需要明确批准，内网服务需要部署管理员允许。",
  "vectorNotConfigured": "尚未配置 Qdrant 后端；向量重建需先完成服务端配置。字面检索仍可使用。",
  "rebuildIndex": "重建我的向量索引",
  "hasKey": "已保存密钥",
  "yes": "是",
  "no": "否",
  "protocol": "接口协议",
  "baseUrl": "模型服务地址",
  "modelName": "模型名称",
  "modelRevision": "模型版本标识",
  "apiKey": "API 密钥（空白保留）",
  "removeKey": "删除已保存的密钥",
  "dimensions": "向量维度",
  "dailyRequests": "每日调用上限",
  "outputTokens": "输出 Token 上限",
  "batchSize": "每批记忆数量",
  "modelSensitivity": "模型允许处理的最高敏感级别",
  "approveEgress": "我允许将所选级别的记忆发送至此模型",
  "approveQuery": "我也允许发送搜索词以进行语义检索",
  "keyWriteOnlyNote": "密钥仅可写入，服务不会返回原密钥。跨站点更换服务地址时，必须重新填写密钥。",
  "probeCostNote": "此测试发送合成文本，不发送个人记忆，但真实模型可能计费，并计入每日限额。",
  "chatgptGrants": "ChatGPT 授权",
  "agentConnections": "Agent 连接",
  "mcpEndpoint": "MCP 地址",
  "expires": "到期时间",
  "addConnection": "添加连接",
  "label": "连接名称",
  "agentId": "Agent 标识",
  "deviceId": "设备标识",
  "access": "访问权限",
  "read": "只读记忆",
  "read_write": "读取和显式保存",
  "rotateKey": "轮换密钥",
  "revoked": "已撤销",
  "active": "有效",
  "managedConnection": "系统／运维管理",
  "accountSecurity": "账户安全操作",
  "changePassword": "修改密码",
  "changeTotp": "更换验证器",
  "rotateRecovery": "重新生成恢复码",
  "securityOperationsNote": "高风险操作需要当前密码和新的动态验证码。修改密码或验证器后，网页会话与 OAuth 授权失效，需要重新登录；独立 Agent 密钥不随普通密码修改自动删除。",
  "sessions": "登录会话",
  "currentSession": "当前会话",
  "revokeOtherSessions": "退出其他会话",
  "reauthenticate": "再次验证身份",
  "currentPassword": "当前密码",
  "newPassword": "新密码",
  "otpFreshNote": "请使用尚未用于登录或其他操作的动态验证码；必要时等待下一组验证码。",
  "invitationLimits": "有效期 1–1440 分钟；本次最大生成数量：",
  "count": "生成数量",
  "ttlMinutes": "有效期（分钟）",
  "revokeBatch": "撤销整批",
  "operatorRequired": "当前账户不是平台管理员，不能访问注册码或其他账户的管理信息。",
  "role": "角色",
  "accountAdminNote": "只管理账户状态和角色，不提供访问其他用户记忆的入口。最后一位管理员受到保护。",
  "maintenanceRequired": "启停账户需要配置本地身份供应与凭证撤销 worker。",
  "enable": "启用",
  "disable": "停用",
  "grantOperator": "授予管理员",
  "revokeOperator": "移除管理员",
  "personalExport": "个人数据迁移",
  "importMemories": "导入个人记忆",
  "file": "导入文件",
  "portableNote": "导出本人原子记忆，不包含其他账户、凭证或整库文件。导入创建新的个人级记忆，不覆盖现有记录；非有效记录保留为撤回状态。来源历史与附件需使用离线完整备份。",
  "databaseRestoreNote": "共享数据库的整库恢复不能从个人控制台执行。运维需使用现有离线备份与隔离恢复命令，并在切换前校验。",
  "exportPrivacyNote": "下载文件包含你的记忆原文。请保存在私有位置，不要提交 GitHub。",
  "confirmImport": "我确认将文件内容导入为新的个人级记忆，不覆盖原记录",
  "importPartial": "已完成导入记录数",
  "operationId": "操作编号",
  "confirmAction": "确认执行此操作？",
  "consoleUpgradeRequired": "此账户仍使用只读核心凭证。请由运维显式升级控制台权限后使用写操作。",
  "recoveryNotConfigured": "网页恢复需要部署管理员配置证明组合与本地身份维护服务；未配置时不开放弱恢复入口。",
  "recoveryAction": "恢复项目",
  "resetPassword": "忘记密码",
  "resetTotp": "丢失验证器",
  "recoveryCode": "一次性恢复码",
  "recoveryProofNote": "重置密码：恢复码＋动态验证码。重置验证器：恢复码＋当前密码。仅填写所需证明；不输入 ChatGPT 密码。",
  "recoveryComplete": "凭证恢复已提交；身份供应完成后可重新登录。",
  "lexical": "字面检索",
  "hybrid": "混合检索",
  "semantic": "语义检索",
  "searchMode": "检索模式",
  "allStatuses": "全部状态",
  "CONSOLE_KEY_REQUIRED": "请先在服务器配置控制台加密密钥",
  "CONSOLE_UPGRADE_REQUIRED": "此账户的核心权限尚未升级",
  "REAUTHENTICATION_FAILED": "身份验证失败，请检查密码并使用新的动态验证码",
  "MEMORY_VERSION_CHANGED": "记忆已更新，请重新打开详情后操作",
  "MODEL_VERSION_CHANGED": "模型设置已更新，请重新打开配置",
  "NOT_CONFIGURED": "尚未启用所需模型",
  "EGRESS_DENIED": "模型外发尚未获准",
  "ADDRESS_DENIED": "目标地址被安全策略拒绝",
  "IDENTITY_MAINTENANCE_REQUIRED": "需要配置本地身份维护服务",
  "LAST_OPERATOR": "不能停用或降级最后一位管理员",
  "IDEMPOTENCY_CONFLICT": "此操作编号已用于不同请求",
  "OPERATION_PENDING": "操作结果尚未确认，请不要换编号重复提交",
  "IMPORT_CONTENT_TOO_LONG": "导入包含超过 4096 字符的记录，请使用离线迁移，未开始本次导入",
  "EDIT_REQUIRES_COMPLETE_RECORD": "超长记录需先完整读取并使用离线修订流程",
  "webVisibilityNote": "查看或修改 ChatGPT 对当前版本的读取许可",
  "memory.create": "新建记忆",
  "memory.correct": "修订记忆",
  "memory.retract": "撤回记忆",
  "memory.classify": "手动分类",
  "memory.sensitivity": "调整敏感级别",
  "memory.visibility": "ChatGPT 读取许可",
  "jobs.schedule": "提交整理任务",
  "jobs.retry": "重试任务",
  "jobs.cancel": "取消任务",
  "models.save": "保存模型设置",
  "models.disable": "停用模型",
  "models.test": "测试模型接口",
  "vector.schedule": "重建个人向量索引",
  "connections.create": "创建 Agent 连接",
  "connections.revoke": "撤销连接",
  "connections.rotate": "轮换连接密钥",
  "oauth.revoke": "撤销 OAuth 授权",
  "security.password": "修改账户密码",
  "security.totp.begin": "更换验证器",
  "security.totp.complete": "验证新验证器",
  "security.recovery_codes": "重新生成恢复码",
  "security.session.revoke": "退出指定会话",
  "security.sessions.revoke_others": "退出其他会话",
  "invitations.issue": "批量签发注册码",
  "invitations.revoke": "撤销注册码",
  "invitations.revoke_batch": "撤销批次",
  "accounts.disable": "停用账户",
  "accounts.enable": "启用账户",
  "accounts.role": "变更管理员角色",
  "storage.export": "导出我的记忆",
  "storage.import": "导入个人记忆"
});
Object.assign(catalog["en"],{
  "interactive": "Interactive",
  "actions": "Actions",
  "refresh": "Refresh",
  "save": "Save",
  "confirm": "Confirm",
  "content": "Memory content",
  "memoryType": "Memory type",
  "topic": "Topic (optional)",
  "scopeTarget": "Scope ID (blank for personal)",
  "user": "Personal",
  "project": "Project",
  "task": "Task",
  "workstream": "Workstream",
  "session": "Session",
  "fact": "Fact",
  "goal": "Goal",
  "constraint": "Constraint",
  "decision": "Decision",
  "completed": "Completed item",
  "blocker": "Blocker",
  "remaining": "Remaining work",
  "next_step": "Next step",
  "editMemory": "Correct memory",
  "retractMemory": "Retract memory",
  "classifyMemory": "Set category",
  "sensitivity": "Sensitivity",
  "webVisibility": "ChatGPT visibility",
  "reason": "Reason",
  "category": "Category",
  "sensitive": "Sensitive",
  "internal": "Internal",
  "public": "Public / egress allowed",
  "secret": "Secret (no egress)",
  "allowChatGPT": "Allow ChatGPT to read this revision",
  "grantRevisionNote": "Approval is pinned to this revision and expires on change. Secret records cannot be granted.",
  "sensitivityNote": "Changing sensitivity revokes the old grant and invalidates derived data. Public records need no individual grant.",
  "retractNote": "Retraction removes active recall while retaining content and history. No physical deletion.",
  "jobType": "Job type",
  "classification": "Classification",
  "summary": "Summary",
  "summarize": "Summarize",
  "timezone": "Time zone",
  "includeOpen": "Include the current open period",
  "enablePeriodic": "Enable periodic classification and daily/weekly summaries",
  "organizeCostNote": "A persistent worker executes this job. Approved model calls may send source text and incur costs. Missing configuration is not reported as success.",
  "scheduleStatus": "Scheduled organization",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "progress": "Progress",
  "cancelJob": "Cancel job",
  "vectorIndex": "Vector index",
  "organizer": "Organizer model",
  "embedder": "Embedding model",
  "testModel": "Test connection",
  "modelBoundary": "Model and data boundary",
  "modelBoundaryNote": "Models belong to this account. Keys are encrypted and never echoed. Egress requires approval; private-network services require operator configuration.",
  "vectorNotConfigured": "Qdrant is not configured. Configure the backend before rebuilding; lexical search remains available.",
  "rebuildIndex": "Rebuild my vector index",
  "hasKey": "Key stored",
  "yes": "Yes",
  "no": "No",
  "protocol": "API protocol",
  "baseUrl": "Model service URL",
  "modelName": "Model name",
  "modelRevision": "Model revision",
  "apiKey": "API key (blank keeps existing)",
  "removeKey": "Remove the stored key",
  "dimensions": "Vector dimensions",
  "dailyRequests": "Daily request ceiling",
  "outputTokens": "Output token limit",
  "batchSize": "Batch size",
  "modelSensitivity": "Highest allowed model sensitivity",
  "approveEgress": "I approve sending selected memory classes to this model",
  "approveQuery": "I also approve sending search queries for semantic retrieval",
  "keyWriteOnlyNote": "Keys are write-only. Changing the service origin clears the old key unless a new key is supplied.",
  "probeCostNote": "This sends synthetic text, not personal memories. The real model may charge and the call counts toward your daily limit.",
  "chatgptGrants": "ChatGPT grants",
  "agentConnections": "Agent connections",
  "mcpEndpoint": "MCP endpoint",
  "expires": "Expires",
  "addConnection": "Add connection",
  "label": "Connection name",
  "agentId": "Agent ID",
  "deviceId": "Device ID",
  "access": "Access",
  "read": "Read memories",
  "read_write": "Read and explicitly save",
  "rotateKey": "Rotate key",
  "revoked": "Revoked",
  "active": "Active",
  "managedConnection": "System / operator managed",
  "accountSecurity": "Account security actions",
  "changePassword": "Change password",
  "changeTotp": "Replace authenticator",
  "rotateRecovery": "Rotate recovery codes",
  "securityOperationsNote": "High-risk actions require the current password and a fresh OTP. Password/MFA changes invalidate browser sessions and OAuth grants. Standalone Agent keys are not deleted by ordinary password changes.",
  "sessions": "Login sessions",
  "currentSession": "Current session",
  "revokeOtherSessions": "Revoke other sessions",
  "reauthenticate": "Reauthenticate",
  "currentPassword": "Current password",
  "newPassword": "New password",
  "otpFreshNote": "Use an OTP not already consumed by login or another action. Wait for the next code when necessary.",
  "invitationLimits": "TTL: 1–1440 minutes. Maximum batch size:",
  "count": "Count",
  "ttlMinutes": "Lifetime (minutes)",
  "revokeBatch": "Revoke batch",
  "operatorRequired": "This account has no operator role. Invitation and account administration is unavailable.",
  "role": "Role",
  "accountAdminNote": "Manage account state and roles only, not other users’ memories. The last operator is protected.",
  "maintenanceRequired": "Account activation/suspension requires the local identity provisioning and revocation worker.",
  "enable": "Enable",
  "disable": "Disable",
  "grantOperator": "Grant operator",
  "revokeOperator": "Remove operator",
  "personalExport": "Personal data portability",
  "importMemories": "Import personal memories",
  "file": "Import file",
  "portableNote": "Exports your atomic memories, not other accounts, credentials or the database. Imports create new personal memories without overwriting records; non-active records remain retracted. Full provenance and attachments require an offline backup.",
  "databaseRestoreNote": "Shared-database restoration is an operator procedure, not a personal console action. Use the existing offline backup and isolated restore commands before switching.",
  "exportPrivacyNote": "The download contains memory text. Store it privately and never commit it to GitHub.",
  "confirmImport": "Import as new personal memories without overwriting originals",
  "importPartial": "Records imported before interruption",
  "operationId": "Operation ID",
  "confirmAction": "Confirm this operation?",
  "consoleUpgradeRequired": "This account still has a read-only Core credential. An operator must explicitly enable console write capabilities.",
  "recoveryNotConfigured": "Web recovery needs operator-configured proof combinations and local identity maintenance. No weak fallback is enabled.",
  "recoveryAction": "Recovery action",
  "resetPassword": "Reset password",
  "resetTotp": "Reset authenticator",
  "recoveryCode": "One-time recovery code",
  "recoveryProofNote": "Password reset: recovery code + OTP. Authenticator reset: recovery code + current password. Fill only the required factors, not your ChatGPT password.",
  "recoveryComplete": "Credentials recovered. Sign in after identity provisioning completes.",
  "lexical": "Lexical",
  "hybrid": "Hybrid",
  "semantic": "Semantic",
  "searchMode": "Search mode",
  "allStatuses": "All statuses",
  "CONSOLE_KEY_REQUIRED": "Configure the console encryption key on the server first",
  "CONSOLE_UPGRADE_REQUIRED": "This account’s Core permissions have not been upgraded",
  "REAUTHENTICATION_FAILED": "Reauthentication failed; check your password and use a fresh OTP",
  "MEMORY_VERSION_CHANGED": "Memory changed; reopen the detail before editing",
  "MODEL_VERSION_CHANGED": "Model settings changed; reopen configuration",
  "NOT_CONFIGURED": "The required model is not enabled",
  "EGRESS_DENIED": "Model egress has not been approved",
  "ADDRESS_DENIED": "The destination address is denied by security policy",
  "IDENTITY_MAINTENANCE_REQUIRED": "Local identity maintenance must be configured",
  "LAST_OPERATOR": "The last operator cannot be disabled or demoted",
  "IDEMPOTENCY_CONFLICT": "This operation ID belongs to another request",
  "OPERATION_PENDING": "Operation outcome is pending; do not resubmit with a new ID",
  "IMPORT_CONTENT_TOO_LONG": "A record exceeds 4096 characters. Use offline migration; this import has not started",
  "EDIT_REQUIRES_COMPLETE_RECORD": "Read the full oversized record and use offline correction",
  "webVisibilityNote": "Inspect or change ChatGPT access to the current revision",
  "memory.create": "Create memory",
  "memory.correct": "Correct memory",
  "memory.retract": "Retract memory",
  "memory.classify": "Classify memory",
  "memory.sensitivity": "Change sensitivity",
  "memory.visibility": "ChatGPT access",
  "jobs.schedule": "Schedule organization",
  "jobs.retry": "Retry job",
  "jobs.cancel": "Cancel job",
  "models.save": "Save model settings",
  "models.disable": "Disable model",
  "models.test": "Test model API",
  "vector.schedule": "Rebuild personal vector index",
  "connections.create": "Create Agent connection",
  "connections.revoke": "Revoke connection",
  "connections.rotate": "Rotate connection key",
  "oauth.revoke": "Revoke OAuth grant",
  "security.password": "Change account password",
  "security.totp.begin": "Replace authenticator",
  "security.totp.complete": "Verify new authenticator",
  "security.recovery_codes": "Rotate recovery codes",
  "security.session.revoke": "Revoke session",
  "security.sessions.revoke_others": "Revoke other sessions",
  "invitations.issue": "Issue invitation codes",
  "invitations.revoke": "Revoke invitation",
  "invitations.revoke_batch": "Revoke invitation batch",
  "accounts.disable": "Disable account",
  "accounts.enable": "Enable account",
  "accounts.role": "Change operator role",
  "storage.export": "Export my memories",
  "storage.import": "Import personal memories"
});

Object.assign(catalog['zh-CN'],{modelNotConfigured:'尚未配置',nativeSchema:'服务支持原生 JSON Schema',searchMode:'检索方式',lexical:'精确检索',hybrid:'混合检索',semantic:'语义检索',workerStatus:'后台执行器',workerDisabledNote:'任务已持久保存。管理员需要启用后台执行器，任务才会运行。'});
Object.assign(catalog.en,{modelNotConfigured:'Not configured',nativeSchema:'Service supports native JSON Schema',searchMode:'Search mode',lexical:'Lexical',hybrid:'Hybrid',semantic:'Semantic',workerStatus:'Worker',workerDisabledNote:'Jobs are stored durably. An operator must enable the worker before queued jobs can run.'});

Object.assign(catalog['zh-CN'],{CSRF_REFRESH_REQUIRED:'表单校验已更新，请重新确认本次操作',EXPORT_SIZE_LIMIT:'导出超过 16 MiB，请使用运维备份或分批导出',BUDGET_EXHAUSTED:'今日模型调用额度已用尽',WEB_VISIBILITY_DENIED:'此分类或版本不允许授权；secret 不会发送给 ChatGPT',CONSOLE_REQUEST_FAILED:'操作未完成，请核对输入和服务状态',MODEL_URL_DENIED:'服务地址不符合网络安全策略'});
Object.assign(catalog.en,{CSRF_REFRESH_REQUIRED:'Form protection refreshed; confirm this operation again',EXPORT_SIZE_LIMIT:'Export exceeds 16 MiB; use operator backup or split exports',BUDGET_EXHAUSTED:'Daily model-call limit reached',WEB_VISIBILITY_DENIED:'This class or revision cannot be granted; secret is never sent to ChatGPT',CONSOLE_REQUEST_FAILED:'Operation did not complete; check input and service state',MODEL_URL_DENIED:'Service URL is denied by network policy'});

Object.assign(catalog['zh-CN'],{
  registrationDisabled:'当前暂未开放注册。请联系平台管理员；已有账户可继续登录。',
  registrationSteps:'创建用户：验证注册码 → 设置用户名与密码 → 绑定验证器 → 保存恢复码。所有步骤完成并绑定核心身份后才能登录。',
  registrationCredentials:'用户名使用 1–100 位英文字母、数字、点、横线、下划线或 @；密码至少 14 位。请使用自己的验证器完成下一步。',
  platform:'平台管理',invitationIdentifier:'注册码 / 批次编号',revocation_pending:'会话已停用；核心凭证撤销处理中，请刷新核验。',
  operatorManagement:'管理员操作',managementDisabled:'此项管理功能尚未由服务器启用。',rolesServerOnly:'角色只能通过服务器命令调整；此页面不能授予管理员权限，也不能查看其他人的记忆。',
  invitationPrivateNote:'注册码为一次性凭证，有效期为 1–1440 整数分钟。仅在签发结果中显示，请通过可信渠道交给接收人。',
  invitationSavedNote:'请现在复制并妥善保存注册码。关闭此窗口后，列表只显示状态，不显示原码。',
  currentAccount:'当前账户',mfaStatus:'动态口令',bindingStatus:'核心身份',verified:'已验证',ready:'就绪',operator:'平台管理员',member:'普通用户',issued:'待使用',reserved:'注册中',consumed:'已使用',provisioning:'绑定中',pending_mfa:'待绑定验证器',
  disableAccountNote:'停用将撤销该账户的登录会话、OAuth 授权和核心凭证。其记忆及历史仍保留，不会删除。',
  enableAccountNote:'重新启用会建立新的账户凭证，不会恢复旧会话或旧密钥；对方需要重新登录与授权。'
});
Object.assign(catalog.en,{
  registrationDisabled:'Registration is currently closed. Contact the platform operator; existing accounts can still sign in.',
  registrationSteps:'Create an account: validate invitation → choose username and password → bind authenticator → save recovery codes. Sign-in requires all steps and a completed Core identity binding.',
  registrationCredentials:'Use 1–100 letters, digits, dots, hyphens, underscores or @ for your username and at least 14 characters for your password. Have your own authenticator ready.',
  platform:'Platform management',invitationIdentifier:'Invitation / batch ID',revocation_pending:'Sessions disabled; Core revocation pending. Refresh to verify completion.',
  operatorManagement:'Operator actions',managementDisabled:'This management feature has not been enabled on the server.',rolesServerOnly:'Roles are managed by server command only. This page cannot grant operator rights or read another account’s memories.',
  invitationPrivateNote:'Codes are single-use credentials, valid for 1–1440 whole minutes. They appear only in the issuance result; share them through a trusted channel.',
  invitationSavedNote:'Copy and securely save these codes now. After this dialog closes, the inventory shows status only, never the original codes.',
  currentAccount:'Current account',mfaStatus:'Authenticator',bindingStatus:'Core identity',verified:'Verified',ready:'Ready',operator:'Platform operator',member:'Member',issued:'Available',reserved:'Registering',consumed:'Used',provisioning:'Provisioning',pending_mfa:'Awaiting authenticator',
  disableAccountNote:'Disabling revokes this account’s sessions, OAuth grants and Core credentials. Memories and history are retained, not deleted.',
  enableAccountNote:'Enabling creates fresh account credentials, not old sessions or keys. The account must sign in and authorize again.'
});

// Neural console: overview visualisations and shell. Counts only; no invented trends.
Object.assign(catalog['zh-CN'],{
 constellationLabel:'记忆星图',constellationTitle:'你的记忆网络',constellationNote:'有效记忆按分类与类型聚合，节点大小对应数量。',
 constellationEmpty:'还没有记忆。连接一个 Agent，新的记忆会在这里汇聚成网络。',
 activityLabel:'近 30 天',activityTitle:'记忆写入活动',activityTotal:'新增',peakDay:'单日峰值',noActivity:'最近 30 天没有新增记忆',
 compositionLabel:'结构',compositionTitle:'类型与生命周期',typesLegend:'记忆类型',lifecycle:'生命周期',categoriesLegend:'分类',
 flowLabel:'处理管线',shortcutSearch:'搜索记忆',consoleStatus:'控制台会话',sessionSecure:'已验证 · 本账户隔离',
});
Object.assign(catalog.en,{
 constellationLabel:'MEMORY CONSTELLATION',constellationTitle:'Your memory network',constellationNote:'Active memories grouped by category and type. Node size reflects count.',
 constellationEmpty:'No memories yet. Connect an agent and new memories will gather here.',
 activityLabel:'LAST 30 DAYS',activityTitle:'Memory activity',activityTotal:'New',peakDay:'Daily peak',noActivity:'No new memories in the last 30 days',
 compositionLabel:'STRUCTURE',compositionTitle:'Types & lifecycle',typesLegend:'Memory types',lifecycle:'Lifecycle',categoriesLegend:'Categories',
 flowLabel:'PIPELINE',shortcutSearch:'Search memories',consoleStatus:'Console session',sessionSecure:'Verified · account isolated',
});

// Workbench UI (memory-centred shell). Later assignments intentionally override older labels.
Object.assign(catalog['zh-CN'],{
 navHome:'首页',navLibrary:'记忆库',navSummaries:'摘要',navJobs:'整理',navSettings:'设置',navMore:'更多设置',
 settingsTitle:'设置',settingsGroupAccount:'连接与账户',settingsGroupSystem:'数据与系统',settingsGroupPlatform:'平台管理',
 homeTitle:'今天想找回什么？',homeNote:'在你授权保存的记忆里搜索；每条结果都能追溯到来源和版本。',askPlaceholder:'搜索记忆里的事实、决定、项目……',
 recentStream:'最近写入',pulseTitle:'记忆概况',activityStrip:'近 30 天写入',pipelineTitle:'整理管线',openLibrary:'打开记忆库',
 libraryHint:'选择一条记忆，在右侧查看正文、来源与修订历史。',filters:'筛选',resultCount:'条结果',closePane:'关闭详情',
 summaryIndex:'分类索引',summaryList:'派生摘要',auditTimeline:'事件时间线',accountPanel:'账户',
 authPoint_source:'每条记忆都保留来源与版本',authPoint_readonly:'第三方应用只获得你逐项授权的只读访问',authPoint_isolation:'账户彼此隔离，登录需要密码和动态验证码',
});
Object.assign(catalog.en,{
 navHome:'Home',navLibrary:'Library',navSummaries:'Summaries',navJobs:'Organize',navSettings:'Settings',navMore:'More settings',
 settingsTitle:'Settings',settingsGroupAccount:'Connections & account',settingsGroupSystem:'Data & system',settingsGroupPlatform:'Platform',
 homeTitle:'What do you want to recall?',homeNote:'Search the memories you chose to keep. Every result traces back to its source and revision.',askPlaceholder:'Search facts, decisions, projects…',
 recentStream:'Recently saved',pulseTitle:'At a glance',activityStrip:'Saved in the last 30 days',pipelineTitle:'Organizer pipeline',openLibrary:'Open library',
 libraryHint:'Select a memory to read its content, sources and revision history on the right.',filters:'Filters',resultCount:'results',closePane:'Close details',
 summaryIndex:'Category index',summaryList:'Derived summaries',auditTimeline:'Event timeline',accountPanel:'Account',
 authPoint_source:'Every memory keeps its source and revision',authPoint_readonly:'Apps get only the read-only access you grant',authPoint_isolation:'Accounts are isolated; sign-in needs a password and a one-time code',
});

// HUD skin: status bar and radar. Status values shown only from real session state.
Object.assign(catalog['zh-CN'],{
 statusClock:'本地时间',statusSession:'会话',sessionVerified:'已验证',statusLink:'核心链路',linkPending:'连接中',linkOnline:'在线',linkDegraded:'异常',
 radarLabel:'记忆雷达',radarTitle:'分类扫描',radarNote:'扇区按有效记忆的分类占比划分，外圈刻度是近 30 天每天的写入量。',radarEmpty:'尚无记忆信号',
 recentStream:'最近写入',openLibrary:'打开记忆库',pulseTitle:'信号概况',pipelineTitle:'整理管线',activityStrip:'近 30 天写入',
});
Object.assign(catalog.en,{
 statusClock:'Local time',statusSession:'Session',sessionVerified:'Verified',statusLink:'Core link',linkPending:'Connecting',linkOnline:'Online',linkDegraded:'Degraded',
 radarLabel:'MEMORY RADAR',radarTitle:'Category sweep',radarNote:'Sectors show each category’s share of active memories; rim ticks are daily saves over the last 30 days.',radarEmpty:'No memory signal yet',
 recentStream:'Recently saved',openLibrary:'Open library',pulseTitle:'Signal overview',pipelineTitle:'Organizer pipeline',activityStrip:'Saved in the last 30 days',
});

// Ink archive: overview distribution and registration steps (override earlier labels).
Object.assign(catalog['zh-CN'],{radarLabel:'记忆分布',radarTitle:'分类构成',radarNote:'圆环按有效记忆的分类占比绘制，中心是有效记忆总数。',radarEmpty:'还没有有效记忆',activeMemories:'有效记忆',
 registrationStepsLabel:'注册步骤',stepInvitation:'验证注册码',stepAccount:'设置账户',stepTotp:'绑定验证器',stepRecovery:'保存恢复码'});
Object.assign(catalog.en,{radarLabel:'Memory distribution',radarTitle:'Category mix',radarNote:'The ring shows each category’s share of active memories; the centre is the total.',radarEmpty:'No active memories yet',activeMemories:'active',
 systemLabel:'Personal memory system',authEyebrow:'Connect to your memory',
 registrationStepsLabel:'Registration steps',stepInvitation:'Invitation',stepAccount:'Account',stepTotp:'Authenticator',stepRecovery:'Recovery codes'});

export const text=(key,locale='zh-CN')=>catalog[locale]?.[key]??catalog.en[key]??key;
