export const catalog={
 'zh-CN':{
  consoleLogin:'登录管理控制台',consoleLoginNote:'管理自己的记忆和连接。此登录不会自动向 ChatGPT 授权。',oauthLogin:'连接 ChatGPT',oauthLoginNote:'先验证你的 Mnemuron 账户，再明确允许只读访问。这不会登录管理控制台。',oauthConsent:'允许 ChatGPT 只读访问',oauthRestartHelp:'此链接只用于本次授权，并非固定的集成页面。请关闭此页，回到 ChatGPT 重新发起连接。',oauthRetry:'重试本次授权',
  overview:'概览',memories:'记忆库',summaries:'分类与摘要',jobs:'整理任务',connections:'连接管理',models:'模型配置',security:'账户安全',audit:'审计记录',storage:'存储与备份',appearance:'外观设置',invitations:'注册码管理',accounts:'账户管理',handoff:'Handoff · 延后',
  workspace:'我的空间',settings:'连接与设置',platform:'平台管理 · 权限待定',brandNote:'个人记忆，持续连接。',hero:'你的记忆，井然有序。',heroNote:'保留每条信息的来源，让上下文在会话间延续。',
  login:'登录 Mnemuron',register:'创建你的账户',recover:'账户恢复',username:'用户名',password:'密码',otp:'动态验证码',invitation:'一次性注册码',continue:'继续',signIn:'登录',signOut:'退出当前会话',cancel:'取消',allow:'允许只读访问',
  authNote:'请使用 Mnemuron 账户，不要输入 ChatGPT 密码。',inviteNote:'注册码由服务器管理员签发，仅可使用一次。',totp:'绑定验证器',totpNote:'使用验证器扫描二维码，或手动输入密钥。密钥只在绑定期间可见。',verify:'验证并继续',copy:'复制',copied:'已复制',showPassword:'显示密码',hidePassword:'隐藏密码',
  recoveryCodes:'保存恢复码',recoveryNote:'这些恢复码仅显示一次。请离线保存，不要上传或分享。',acknowledge:'我已保存恢复码',pending:'正在等待安全绑定',pendingNote:'MFA 已验证。核心身份供应与恢复码确认全部完成后才能登录。',registered:'注册完成，请正常登录',
  blocked:'策略待确认',blockedNote:'此操作尚未获准。页面展示不代表操作已开放。',unavailable:'暂不可用',retry:'重试',loading:'正在加载…',empty:'目前没有可显示的记录',noConnection:'尚无已授权连接',authenticated:'已验证账户',restartAuthorization:'账户或授权会话已变化。请返回请求连接的应用，重新发起授权。',
  search:'搜索记忆',query:'搜索内容',readOnly:'只读',memoryCount:'原子记忆',sourceCount:'来源记录',summaryCount:'摘要',jobCount:'整理任务',recent:'最近的记忆',viewAll:'查看全部',detail:'记忆详情',sources:'来源',revisions:'版本',next:'下一页',previous:'上一页',close:'关闭',complete:'内容已完整读取',changed:'来源或版本已变化，请重新读取。',
  appearanceNote:'配色不改变布局、功能或权限。偏好按账户分别保存。',theme:'颜色主题',mode:'明暗模式',language:'语言',light:'浅色',dark:'深色',a:'Neural Indigo',b:'Signal Teal',c:'Paper Amber',
  securityNote:'登录需要密码与动态验证码。恢复证明组合尚待确认，不启用弱恢复。',modelsNote:'模型资源与费用策略待确认。不显示密钥或其他账户配置。',storageNote:'只展示本人记录的统计。整库备份、恢复与下载不在网页权限内。',platformNote:'当前账户没有平台管理授权。此页不返回其他账户的身份或统计。',
  error:'请求未完成',errorNote:'请返回并重试。未授权、过期或依赖故障不会跳过安全校验。',identity:'当前账户',state:'状态',created:'创建时间',scope:'范围',status:'状态',consent:'授权连接',consentNote:'仅允许读取你授权的记忆和项目。不会写入记忆、切换任务或确认 Resume。',
  policy:'权限边界',pendingPolicies:'未批准操作保持关闭',notProduction:'尚未生产晋级',noDemo:'所有数据来自当前账户；不可用时不会显示演示数据。',newMemory:'新建记忆',organize:'手动整理',export:'导出记忆',restore:'整库恢复',configure:'修改配置',issue:'网页签发',manage:'角色管理',revoke:'撤销授权',
  passwordConfirm:'再次输入密码',alreadyShown:'密钥已显示过。本页不会重新展示；请使用已保存的验证器或恢复码。',oauthClient:'请求连接的应用',scopeIdentity:'识别你的 Mnemuron 账户',scopeOffline:'使用可撤销、轮换的刷新令牌保持连接',scopeMemory:'读取你授权的记忆',scopeProject:'读取你授权的项目上下文',systemLabel:'个人记忆系统',workspaceLabel:'个人工作空间',heroLabel:'让记忆持续连接',passwordTotp:'密码与动态验证码',back:'返回安全入口',expired:'此步骤已过期，请从安全入口重新开始。',loginFailed:'登录信息无效或账户尚不可用。请检查凭证后重试。',rateLimited:'尝试过于频繁，请稍后重试。',pendingStep:'此步骤暂不可用，请重新检查当前注册状态。',
 },
 en:{
  consoleLogin:'Sign in to the console',consoleLoginNote:'Manage your memories and connections. This sign-in does not authorize ChatGPT.',oauthLogin:'Connect ChatGPT',oauthLoginNote:'Verify your Mnemuron account, then explicitly allow read-only access. This does not sign you in to the console.',oauthConsent:'Allow ChatGPT read-only access',oauthRestartHelp:'This link belongs to one authorization request, not a permanent integration page. Close this page and start a new connection from ChatGPT.',oauthRetry:'Retry this authorization',
  overview:'Overview',memories:'Memory library',summaries:'Categories & summaries',jobs:'Organizer jobs',connections:'Connections',models:'Model settings',security:'Account security',audit:'Audit log',storage:'Storage & backup',appearance:'Appearance',invitations:'Registration codes',accounts:'Accounts',handoff:'Handoff · deferred',
  workspace:'My workspace',settings:'Connections & settings',platform:'Platform · policy pending',brandNote:'Personal memory. Lasting context.',hero:'Your memory, thoughtfully organized.',heroNote:'Keep the provenance of every detail. Carry context across conversations.',
  login:'Sign in to Mnemuron',register:'Create your account',recover:'Account recovery',username:'Username',password:'Password',otp:'Authenticator code',invitation:'One-time registration code',continue:'Continue',signIn:'Sign in',signOut:'Sign out of this session',cancel:'Cancel',allow:'Allow read-only access',
  authNote:'Use your Mnemuron account, not your ChatGPT password.',inviteNote:'Registration codes are issued by your operator and can only be used once.',totp:'Connect your authenticator',totpNote:'Scan the QR code or enter the key manually. The key is available only during enrollment.',verify:'Verify and continue',copy:'Copy',copied:'Copied',showPassword:'Show password',hidePassword:'Hide password',
  recoveryCodes:'Save your recovery codes',recoveryNote:'These codes are shown once. Store them offline. Do not upload or share them.',acknowledge:'I have saved my recovery codes',pending:'Waiting for secure identity binding',pendingNote:'MFA is verified. Login requires completed Core provisioning and recovery-code acknowledgement.',registered:'Registration complete. Please sign in.',
  blocked:'Policy pending',blockedNote:'This operation has not been approved. Visibility does not grant permission.',unavailable:'Currently unavailable',retry:'Retry',loading:'Loading…',empty:'No records to display yet',noConnection:'No authorized connection yet',authenticated:'Verified account',restartAuthorization:'The account or authorization session changed. Return to the requesting application and start a new authorization.',
  search:'Search memories',query:'Search query',readOnly:'Read-only',memoryCount:'Atomic memories',sourceCount:'Source records',summaryCount:'Summaries',jobCount:'Organizer jobs',recent:'Recent memories',viewAll:'View all',detail:'Memory detail',sources:'Sources',revisions:'Revision',next:'Next page',previous:'Previous page',close:'Close',complete:'Complete content returned',changed:'The source or revision changed. Read it again.',
  appearanceNote:'Colors never change layout, capabilities or permissions. Preferences are stored per account.',theme:'Color theme',mode:'Color mode',language:'Language',light:'Light',dark:'Dark',a:'Neural Indigo',b:'Signal Teal',c:'Paper Amber',
  securityNote:'Sign-in requires a password and authenticator code. Recovery proof policy is pending; no weaker recovery is enabled.',modelsNote:'Model resources and cost policy are pending. Keys and other accounts’ configuration are never shown.',storageNote:'Only your record totals are shown. Whole-database backup, restore and download are not web capabilities.',platformNote:'This account has no platform management grant. This page returns no other account identities or statistics.',
  error:'Request not completed',errorNote:'Go back and try again. Authorization, expiry and dependency checks are never bypassed.',identity:'Current account',state:'State',created:'Created',scope:'Scope',status:'Status',consent:'Authorize connection',consentNote:'Read only memories and projects you authorize. No memory writes, task switching or Resume confirmation.',
  policy:'Permission boundary',pendingPolicies:'Unapproved operations stay disabled',notProduction:'Not promoted to production',noDemo:'All data belongs to the current account. No demo fallback when unavailable.',newMemory:'New memory',organize:'Run organizer',export:'Export memories',restore:'Restore database',configure:'Change settings',issue:'Issue in browser',manage:'Manage roles',revoke:'Revoke grant',
  passwordConfirm:'Confirm password',alreadyShown:'The secret was already displayed. It is not shown again; use your saved authenticator or recovery codes.',oauthClient:'Application requesting access',scopeIdentity:'Identify your Mnemuron account',scopeOffline:'Keep this connection with revocable, rotating refresh tokens',scopeMemory:'Read memories you authorize',scopeProject:'Read project context you authorize',systemLabel:'PERSONAL MEMORY SYSTEM',workspaceLabel:'PERSONAL WORKSPACE',heroLabel:'YOUR MEMORY, CONNECTED',passwordTotp:'Password and authenticator code',back:'Return to the safe entry point',expired:'This step expired. Start again from the safe entry point.',loginFailed:'The sign-in details or account are unavailable. Check your credentials and try again.',rateLimited:'Too many attempts. Please try again later.',pendingStep:'This step is unavailable. Check your current registration status.',
 }
};

// Presentation copy is separate from backend status codes and never translates memory content.
Object.assign(catalog['zh-CN'], {
  connectionHeadline:'ChatGPT，接上你的个人记忆。', connectionDescription:'从已授权的记忆中找回上下文。来源、版本与访问范围，始终清晰可查。',
  manageConnections:'管理我的连接', browseMemories:'浏览记忆', ownedRecords:'仅当前账户', recentLabel:'近期记忆', processingLabel:'整理概况',
  memoryProcessing:'记忆整理', atomicNote:'保留原文与版本', derivedNote:'来源关联的派生视图', jobStatusNote:'进入任务页查看执行状态',
  summaryBoundary:'摘要是派生视图，不覆盖原文。遗漏与待核实信息保留在来源中。', viewJobs:'查看整理任务', inspectMemoryNote:'点开任意记忆，查看正文、来源与修订历史。',
  personalizeLabel:'个性化工作空间', fixedLayout:'A · 统一布局', themeName_a:'神经靛蓝', themeName_b:'信号青绿', themeName_c:'纸感琥珀',
  themeNote_a:'柔和靛蓝，清晰专注', themeNote_b:'自然青绿，沉稳明快', themeNote_c:'温暖琥珀，舒适阅读',
  modeNote:'选择适合当前环境的明暗模式。', languageNote:'仅切换界面语言，记忆正文保持原样。',
  appearanceScopeNote:'外观偏好独立保存于当前账户。切换不会改变数据、访问权限或正在填写的内容。',
  authHeadlineFirst:'记住重要的。', authHeadlineSecond:'只属于你的。', authDescription:'用一个独立空间连接你的记忆，让每次对话从理解开始。',
  authEyebrow:'连接到你的记忆空间', accountMenu:'当前账户与退出', authFooter:'Mnemuron · 个人记忆，持续上下文',
  pageNote_memories:'搜索、查看并追溯属于你的每一条记忆。', pageNote_summaries:'分类整理与来源关联的摘要，始终与原始记忆分开。',
  pageNote_jobs:'查看整理任务的进度、结果与需要处理的问题。', pageNote_connections:'在同一处查看你的应用授权和 Agent 连接。',
  pageNote_models:'查看模型配置边界与外发政策。密钥不会在页面回显。', pageNote_security:'管理你的身份、验证器与账户访问。',
  pageNote_audit:'仅查看当前账户的访问与安全事件。', pageNote_storage:'了解个人记录与存储边界。个人数据不等于整库备份。',
  pageNote_appearance:'一种布局，多种心境。让你的记忆空间更适合你。', pageNote_invitations:'查看注册准入规则。签发能力由明确的运维权限控制。',
  pageNote_accounts:'账户管理与个人记忆读取相互独立。',
});
Object.assign(catalog.en, {
  connectionHeadline:'Connect ChatGPT to your personal memory.', connectionDescription:'Find context in memories you authorize. Keep every source, revision and access boundary in view.',
  manageConnections:'Manage my connections', browseMemories:'Browse memories', ownedRecords:'This account only', recentLabel:'RECENT MEMORIES', processingLabel:'PROCESSING',
  memoryProcessing:'Memory organization', atomicNote:'Originals and revisions retained', derivedNote:'Source-linked derived views', jobStatusNote:'Open jobs for execution status',
  summaryBoundary:'Summaries are derived views, not replacements for originals. Check sources for omissions and uncertainty.', viewJobs:'View organizer jobs', inspectMemoryNote:'Open a memory to inspect its content, provenance and revision history.',
  personalizeLabel:'PERSONALIZE YOUR WORKSPACE', fixedLayout:'A · Unified layout', themeName_a:'Neural Indigo', themeName_b:'Signal Teal', themeName_c:'Paper Amber',
  themeNote_a:'Soft indigo. Clear focus.', themeNote_b:'Natural teal. Quiet clarity.', themeNote_c:'Warm amber. Thoughtful reading.',
  modeNote:'Choose the appearance that suits your environment.', languageNote:'Translate the interface, never your original memories.',
  appearanceScopeNote:'Appearance preferences belong to this account. Switching never changes data, access permissions or your current form.',
  authHeadlineFirst:'Remember what matters.', authHeadlineSecond:'Keep it yours.', authDescription:'An independent space for your memories. Start every conversation with context.',
  authEyebrow:'CONNECT TO YOUR MEMORY', accountMenu:'Current account and sign out', authFooter:'Mnemuron · Personal memory, continuous context',
  pageNote_memories:'Search, inspect and trace every memory in your own space.', pageNote_summaries:'Source-linked categories and summaries, kept separate from original memories.',
  pageNote_jobs:'Inspect organizer progress, results and items that need attention.', pageNote_connections:'Review your application grants and Agent connections in one place.',
  pageNote_models:'Review model boundaries and egress policy. Secret keys are never displayed.', pageNote_security:'Your identity, authenticator and account access.',
  pageNote_audit:'Access and security events for the current account only.', pageNote_storage:'Understand your record totals. Personal data is not a whole-database backup.',
  pageNote_appearance:'One layout, a different mood. Make this memory space yours.', pageNote_invitations:'Review registration rules. Issuance requires explicit operator permission.',
  pageNote_accounts:'Account administration does not grant access to personal memories.',
});

export const text=(key,locale='zh-CN')=>catalog[locale]?.[key]??catalog.en[key]??key;
